version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    reviewers:
      - founders
    assignees:
      - founders
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    reviewers:
      - founders
    assignees:
      - founders
    commit-message:
      prefix: ci
      include: scope
    groups:
      ci-dependencies:
        patterns:
          - "*"
