# These are supported funding model platforms

github: [finatic-team]
patreon: finatic
open_collective: finatic
ko_fi: finatic
tidelift: finatic
custom: ['https://finatic.dev/support', 'https://finatic.dev/donate']
