/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { FDXConsentGrantCreate } from '../models';
// @ts-ignore
import type { FinaticAPIErrorResponse } from '../models';
// @ts-ignore
import type { FinaticResponseFDXConsentGrant } from '../models';
// @ts-ignore
import type { FinaticResponseListFDXConsentGrant } from '../models';
/**
 * ConsentsApi - axios parameter creator
 */
export const ConsentsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * List FDX consent grants for the current company account.
     * @summary List Consents
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetConsents: async (
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/consents`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get one FDX consent grant for the current company account.
     * @summary Get Consent
     * @param {string} consentId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetConsentsConsentId: async (
      consentId: string,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'consentId' is not null or undefined
      assertParamExists('finaticV1GetConsentsConsentId', 'consentId', consentId);
      const localVarPath = `/api/v1/consents/{consentId}`.replace(
        '{consentId}',
        encodeURIComponent(String(consentId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Create an FDX consent grant for the current company account.
     * @summary Create Consent
     * @param {FDXConsentGrantCreate} fDXConsentGrantCreate
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostConsents: async (
      fDXConsentGrantCreate: FDXConsentGrantCreate,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'fDXConsentGrantCreate' is not null or undefined
      assertParamExists('finaticV1PostConsents', 'fDXConsentGrantCreate', fDXConsentGrantCreate);
      const localVarPath = `/api/v1/consents`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        fDXConsentGrantCreate,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Revoke one FDX consent grant for the current company account.
     * @summary Revoke Consent
     * @param {string} consentId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostConsentsConsentIdRevoke: async (
      consentId: string,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'consentId' is not null or undefined
      assertParamExists('finaticV1PostConsentsConsentIdRevoke', 'consentId', consentId);
      const localVarPath = `/api/v1/consents/{consentId}/revoke`.replace(
        '{consentId}',
        encodeURIComponent(String(consentId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ConsentsApi - functional programming interface
 */
export const ConsentsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ConsentsApiAxiosParamCreator(configuration);
  return {
    /**
     * List FDX consent grants for the current company account.
     * @summary List Consents
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetConsents(
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListFDXConsentGrant>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetConsents(
        xFinaticEnvironment,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentsApi.finaticV1GetConsents']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get one FDX consent grant for the current company account.
     * @summary Get Consent
     * @param {string} consentId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetConsentsConsentId(
      consentId: string,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseFDXConsentGrant>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetConsentsConsentId(
        consentId,
        xFinaticEnvironment,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentsApi.finaticV1GetConsentsConsentId']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Create an FDX consent grant for the current company account.
     * @summary Create Consent
     * @param {FDXConsentGrantCreate} fDXConsentGrantCreate
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1PostConsents(
      fDXConsentGrantCreate: FDXConsentGrantCreate,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseFDXConsentGrant>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1PostConsents(
        fDXConsentGrantCreate,
        xFinaticEnvironment,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentsApi.finaticV1PostConsents']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Revoke one FDX consent grant for the current company account.
     * @summary Revoke Consent
     * @param {string} consentId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1PostConsentsConsentIdRevoke(
      consentId: string,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseFDXConsentGrant>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1PostConsentsConsentIdRevoke(
          consentId,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConsentsApi.finaticV1PostConsentsConsentIdRevoke']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ConsentsApi - factory interface
 */
export const ConsentsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = ConsentsApiFp(configuration);
  return {
    /**
     * List FDX consent grants for the current company account.
     * @summary List Consents
     * @param {ConsentsApiFinaticV1GetConsentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetConsents(
      requestParameters: ConsentsApiFinaticV1GetConsentsRequest = {},
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListFDXConsentGrant> {
      return localVarFp
        .finaticV1GetConsents(requestParameters.xFinaticEnvironment, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get one FDX consent grant for the current company account.
     * @summary Get Consent
     * @param {ConsentsApiFinaticV1GetConsentsConsentIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetConsentsConsentId(
      requestParameters: ConsentsApiFinaticV1GetConsentsConsentIdRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseFDXConsentGrant> {
      return localVarFp
        .finaticV1GetConsentsConsentId(
          requestParameters.consentId,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Create an FDX consent grant for the current company account.
     * @summary Create Consent
     * @param {ConsentsApiFinaticV1PostConsentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostConsents(
      requestParameters: ConsentsApiFinaticV1PostConsentsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseFDXConsentGrant> {
      return localVarFp
        .finaticV1PostConsents(
          requestParameters.fDXConsentGrantCreate,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Revoke one FDX consent grant for the current company account.
     * @summary Revoke Consent
     * @param {ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostConsentsConsentIdRevoke(
      requestParameters: ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseFDXConsentGrant> {
      return localVarFp
        .finaticV1PostConsentsConsentIdRevoke(
          requestParameters.consentId,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ConsentsApi - interface
 */
export interface ConsentsApiInterface {
  /**
   * List FDX consent grants for the current company account.
   * @summary List Consents
   * @param {ConsentsApiFinaticV1GetConsentsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetConsents(
    requestParameters?: ConsentsApiFinaticV1GetConsentsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListFDXConsentGrant>;

  /**
   * Get one FDX consent grant for the current company account.
   * @summary Get Consent
   * @param {ConsentsApiFinaticV1GetConsentsConsentIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetConsentsConsentId(
    requestParameters: ConsentsApiFinaticV1GetConsentsConsentIdRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseFDXConsentGrant>;

  /**
   * Create an FDX consent grant for the current company account.
   * @summary Create Consent
   * @param {ConsentsApiFinaticV1PostConsentsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1PostConsents(
    requestParameters: ConsentsApiFinaticV1PostConsentsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseFDXConsentGrant>;

  /**
   * Revoke one FDX consent grant for the current company account.
   * @summary Revoke Consent
   * @param {ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1PostConsentsConsentIdRevoke(
    requestParameters: ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseFDXConsentGrant>;
}

/**
 * Request parameters for finaticV1GetConsents operation in ConsentsApi.
 */
export interface ConsentsApiFinaticV1GetConsentsRequest {
  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetConsentsConsentId operation in ConsentsApi.
 */
export interface ConsentsApiFinaticV1GetConsentsConsentIdRequest {
  readonly consentId: string;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1PostConsents operation in ConsentsApi.
 */
export interface ConsentsApiFinaticV1PostConsentsRequest {
  readonly fDXConsentGrantCreate: FDXConsentGrantCreate;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1PostConsentsConsentIdRevoke operation in ConsentsApi.
 */
export interface ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest {
  readonly consentId: string;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * ConsentsApi - object-oriented interface
 */
export class ConsentsApi extends BaseAPI implements ConsentsApiInterface {
  /**
   * List FDX consent grants for the current company account.
   * @summary List Consents
   * @param {ConsentsApiFinaticV1GetConsentsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetConsents(
    requestParameters: ConsentsApiFinaticV1GetConsentsRequest = {},
    options?: RawAxiosRequestConfig
  ) {
    return ConsentsApiFp(this.configuration)
      .finaticV1GetConsents(requestParameters.xFinaticEnvironment, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get one FDX consent grant for the current company account.
   * @summary Get Consent
   * @param {ConsentsApiFinaticV1GetConsentsConsentIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetConsentsConsentId(
    requestParameters: ConsentsApiFinaticV1GetConsentsConsentIdRequest,
    options?: RawAxiosRequestConfig
  ) {
    return ConsentsApiFp(this.configuration)
      .finaticV1GetConsentsConsentId(
        requestParameters.consentId,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create an FDX consent grant for the current company account.
   * @summary Create Consent
   * @param {ConsentsApiFinaticV1PostConsentsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1PostConsents(
    requestParameters: ConsentsApiFinaticV1PostConsentsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return ConsentsApiFp(this.configuration)
      .finaticV1PostConsents(
        requestParameters.fDXConsentGrantCreate,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Revoke one FDX consent grant for the current company account.
   * @summary Revoke Consent
   * @param {ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1PostConsentsConsentIdRevoke(
    requestParameters: ConsentsApiFinaticV1PostConsentsConsentIdRevokeRequest,
    options?: RawAxiosRequestConfig
  ) {
    return ConsentsApiFp(this.configuration)
      .finaticV1PostConsentsConsentIdRevoke(
        requestParameters.consentId,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
