/**
 * Custom FinaticServer extension.
 *
 * This file is protected and will not be overwritten during regeneration.
 * Add custom logic to extend or override generated FinaticServer behavior.
 */

import { FinaticServer as GeneratedFinaticServer } from '../generated/FinaticServer';

/**
 * Custom FinaticServer class that extends the generated class.
 * Use this to add custom initialization logic or override methods.
 * 
 * NOTE: All convenience methods (getOpenPositions, getPendingOrders, getActiveAccounts, etc.)
 * are now generated by the generator with proper enum coercion.
 * No custom code needed - this is just a stub for future customizations.
 */
export class FinaticServer extends GeneratedFinaticServer {
  // Marker to verify custom class is being used
  static readonly __CUSTOM_CLASS__ = true;

  // Generator now handles:
  // - All convenience methods (getOpenPositions, getPendingOrders, getActiveAccounts, etc.)
  // - Session headers for broker endpoints
  // - Portal URL no-cache handling
  // - Metadata transformation for withMetadata parameter
  // - Enum coercion (case-insensitive, no aliases)
  // No custom code needed - this is just a stub for future customizations
}

