/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Assettype } from './assettype';
// May contain unused imports in some cases
// @ts-ignore
import type { Closedquantity } from './closedquantity';
// May contain unused imports in some cases
// @ts-ignore
import type { Closepriceavg } from './closepriceavg';
// May contain unused imports in some cases
// @ts-ignore
import type { Costbasis1 } from './costbasis1';
// May contain unused imports in some cases
// @ts-ignore
import type { Costbasiswithcommission1 } from './costbasiswithcommission1';
// May contain unused imports in some cases
// @ts-ignore
import type { FDXBrokerPositionLotFill } from './fdxbroker-position-lot-fill';
// May contain unused imports in some cases
// @ts-ignore
import type { Openprice } from './openprice';
// May contain unused imports in some cases
// @ts-ignore
import type { Openquantity } from './openquantity';
// May contain unused imports in some cases
// @ts-ignore
import type { Realizedprofitloss1 } from './realizedprofitloss1';
// May contain unused imports in some cases
// @ts-ignore
import type { Realizedprofitlosswithcommission1 } from './realizedprofitlosswithcommission1';
// May contain unused imports in some cases
// @ts-ignore
import type { Remainingquantity1 } from './remainingquantity1';
// May contain unused imports in some cases
// @ts-ignore
import type { Side3 } from './side3';

/**
 * FDX-style position lot schema for tax lot tracking.  Represents tax lots for positions, used for tax reporting and FIFO/LIFO tracking.
 */
export interface FDXBrokerPositionLot {
  _id?: string;
  /**
   * Lot identifier
   */
  lotId: string;
  positionId?: string | null;
  /**
   * Broker account identifier
   */
  accountId: string;
  internalAccountId?: string | null;
  connectionId?: string | null;
  /**
   * Security identifier
   */
  securityId: string;
  assetType: Assettype;
  side?: Side3 | null;
  /**
   * When lot was opened
   */
  openedAt: string;
  closedAt?: string | null;
  openQuantity: Openquantity;
  remainingQuantity: Remainingquantity1;
  closedQuantity: Closedquantity;
  openPrice: Openprice;
  closePriceAvg?: Closepriceavg | null;
  costBasis: Costbasis1;
  costBasisWithCommission: Costbasiswithcommission1;
  realizedProfitLoss: Realizedprofitloss1;
  realizedProfitLossWithCommission: Realizedprofitlosswithcommission1;
  /**
   * Fills associated with this lot
   */
  positionLotFills?: Array<FDXBrokerPositionLotFill>;
  metadata?: { [key: string]: any } | null;
}
