/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Futures limit order with NinjaTrader-specific extras.
 */
export interface NinjaTraderFutureLimitOrderPlaceQueryParams {
  [key: string]: any;

  orderType: NinjaTraderFutureLimitOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: NinjaTraderFutureLimitOrderPlaceQueryParamsAssetTypeEnum;
  action: NinjaTraderFutureLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: number;
  price: number;
  accountSpec?: string | null;
  isAutomated?: boolean;
  activationTime?: string | null;
  text?: string | null;
  pegDifference?: number | null;
}

export enum NinjaTraderFutureLimitOrderPlaceQueryParamsOrderTypeEnum {
  Limit = 'limit',
}
export enum NinjaTraderFutureLimitOrderPlaceQueryParamsAssetTypeEnum {
  Future = 'future',
}
export enum NinjaTraderFutureLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
