/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TastyTradeEquityLimitOrderPlaceQueryParams } from './tasty-trade-equity-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TastyTradeEquityMarketOrderPlaceQueryParams } from './tasty-trade-equity-market-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TastyTradeEquityStopOrderPlaceQueryParams } from './tasty-trade-equity-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TastyTradeEquityTrailingStopOrderPlaceQueryParams } from './tasty-trade-equity-trailing-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * @type Order3OneOf
 */
export type Order3OneOf =
  | ({ orderType: 'limit' } & TastyTradeEquityLimitOrderPlaceQueryParams)
  | ({ orderType: 'market' } & TastyTradeEquityMarketOrderPlaceQueryParams)
  | ({ orderType: 'stop' } & TastyTradeEquityStopOrderPlaceQueryParams)
  | ({ orderType: 'trailing_stop' } & TastyTradeEquityTrailingStopOrderPlaceQueryParams);
