/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Order4OneOf } from './order4-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { Order4OneOf1 } from './order4-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { Order4OneOf2 } from './order4-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * @type Order4
 */
export type Order4 = Order4OneOf | Order4OneOf1 | Order4OneOf2;
