/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaOptionLimitOrderPlaceQueryParams } from './alpaca-option-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaOptionMarketOrderPlaceQueryParams } from './alpaca-option-market-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { Notional1 } from './notional1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * @type OrderOneOf1
 */
export type OrderOneOf1 =
  | ({ orderType: 'limit' } & AlpacaOptionLimitOrderPlaceQueryParams)
  | ({ orderType: 'market' } & AlpacaOptionMarketOrderPlaceQueryParams);
