/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber } from './accountnumber';
// May contain unused imports in some cases
// @ts-ignore
import type { RobinhoodOrderCancelQueryParams } from './robinhood-order-cancel-query-params';

/**
 * Robinhood cancel-order request body.  Attributes ---------- broker : Literal[\"robinhood\"]     Discriminator; must be ``\"robinhood\"``. account_number : str | int     Broker-provided account number (top-level). Serialized as ``accountNumber``. order : RobinhoodOrderCancelQueryParamsUnion     Robinhood-specific cancel parameters (e.g. order identifier).  Notes ----- Uses ``extra=\"forbid\"`` and ``populate_by_name=True``.
 */
export interface RobinhoodOrderCancelRequest {
  broker: RobinhoodOrderCancelRequestBrokerEnum;
  accountNumber: Accountnumber;
  order: RobinhoodOrderCancelQueryParams;
}

export enum RobinhoodOrderCancelRequestBrokerEnum {
  Robinhood = 'robinhood',
}
