/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber } from './accountnumber';
// May contain unused imports in some cases
// @ts-ignore
import type { Order2 } from './order2';

/**
 * Robinhood place-order request body.  Attributes ---------- broker : Literal[\"robinhood\"]     Discriminator; must be ``\"robinhood\"``. account_number : str | int     Broker-provided account number (top-level). Serialized as ``accountNumber``. order : RobinhoodOrderPlaceQueryParamsUnion     Robinhood-specific order parameters (equity, equity_option, or crypto wire schema).  Notes ----- Uses ``extra=\"forbid\"`` and ``populate_by_name=True``. JSON schema examples are attached in model_config for OpenAPI docs.
 */
export interface RobinhoodOrderPlaceRequest {
  broker: RobinhoodOrderPlaceRequestBrokerEnum;
  accountNumber: Accountnumber;
  order: Order2;
}

export enum RobinhoodOrderPlaceRequestBrokerEnum {
  Robinhood = 'robinhood',
}
