/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood equity stop-limit order (stopPrice + limitPrice).
 */
export interface RobinhoodEquityStopLimitOrderPlaceQueryParams {
  [key: string]: any;

  assetType: RobinhoodEquityStopLimitOrderPlaceQueryParamsAssetTypeEnum;
  orderQty: number;
  /**
   * Allow trading during extended hours (premium users only)
   */
  extendedHours?: boolean;
  /**
   * Market hours to trade in
   */
  marketHours?: RobinhoodEquityStopLimitOrderPlaceQueryParamsMarketHoursEnum;
  orderType: RobinhoodEquityStopLimitOrderPlaceQueryParamsOrderTypeEnum;
  action: RobinhoodEquityStopLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  stopPrice: number;
  limitPrice: number;
}

export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsAssetTypeEnum {
  Equity = 'equity',
  EquityOption = 'equity_option',
  Crypto = 'crypto',
  Forex = 'forex',
  Future = 'future',
  FutureOption = 'future_option',
  Bond = 'bond',
}
export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsMarketHoursEnum {
  RegularHours = 'regular_hours',
  AllDayHours = 'all_day_hours',
  ExtendedHours = 'extended_hours',
}
export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsOrderTypeEnum {
  StopLimit = 'stop_limit',
}
export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
