/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SuccessPayloadListFDXBrokerTransaction {
  _id?: string;
  /**
   * The response data (None when error is present)
   */
  data?: Array<any> | null;
  /**
   * Optional metadata (pagination, etc.)
   */
  meta?: { [key: string]: any } | null;
}
