/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { AccountOrderCommandRequest } from '../models';
// @ts-ignore
import type { FinaticAPIErrorResponse } from '../models';
// @ts-ignore
import type { FinaticResponseDictStrAny } from '../models';
// @ts-ignore
import type { FinaticResponseFDXBrokerOrderCommandResult } from '../models';
// @ts-ignore
import type { FinaticResponseListDictStrAny } from '../models';
/**
 * AccountsApi - axios parameter creator
 */
export const AccountsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Cancel an account-scoped order.
     * @summary Cancel Account Order
     * @param {string} accountId
     * @param {string} orderId
     * @param {string} idempotencyKey
     * @param {string | null} [broker] Optional broker id hint; must match account grant if set.
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1DeleteAccountsAccountIdOrdersOrderId: async (
      accountId: string,
      orderId: string,
      idempotencyKey: string,
      broker?: string | null,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1DeleteAccountsAccountIdOrdersOrderId', 'accountId', accountId);
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('finaticV1DeleteAccountsAccountIdOrdersOrderId', 'orderId', orderId);
      // verify required parameter 'idempotencyKey' is not null or undefined
      assertParamExists(
        'finaticV1DeleteAccountsAccountIdOrdersOrderId',
        'idempotencyKey',
        idempotencyKey
      );
      const localVarPath = `/api/v1/accounts/{accountId}/orders/{orderId}`
        .replace('{accountId}', encodeURIComponent(String(accountId)))
        .replace('{orderId}', encodeURIComponent(String(orderId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (broker !== undefined) {
        localVarQueryParameter['broker'] = broker;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (idempotencyKey != null) {
        localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
      }
      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List broker accounts visible through active account grants.
     * @summary List Accounts
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccounts: async (
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/accounts`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get one broker account visible through an active account grant.
     * @summary Get Account
     * @param {string} accountId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountId: async (
      accountId: string,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountId', 'accountId', accountId);
      const localVarPath = `/api/v1/accounts/{accountId}`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List account-scoped balances.
     * @summary List Account Balances
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdBalances: async (
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdBalances', 'accountId', accountId);
      const localVarPath = `/api/v1/accounts/{accountId}/balances`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Return JSON Schema for broker-specific order fields for this account.
     * @summary Get Account Order Schema
     * @param {string} accountId
     * @param {string} action Order command action: place, modify, or cancel.
     * @param {string | null} [broker] Optional broker id hint; must match account grant if set.
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrderSchemas: async (
      accountId: string,
      action: string,
      broker?: string | null,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrderSchemas', 'accountId', accountId);
      // verify required parameter 'action' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrderSchemas', 'action', action);
      const localVarPath = `/api/v1/accounts/{accountId}/order-schemas`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (action !== undefined) {
        localVarQueryParameter['action'] = action;
      }

      if (broker !== undefined) {
        localVarQueryParameter['broker'] = broker;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List account-scoped orders.
     * @summary List Account Orders
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrders: async (
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrders', 'accountId', accountId);
      const localVarPath = `/api/v1/accounts/{accountId}/orders`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get one order after account-grant authorization.
     * @summary Get Account Order
     * @param {string} accountId
     * @param {string} orderId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrdersOrderId: async (
      accountId: string,
      orderId: string,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrdersOrderId', 'accountId', accountId);
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrdersOrderId', 'orderId', orderId);
      const localVarPath = `/api/v1/accounts/{accountId}/orders/{orderId}`
        .replace('{accountId}', encodeURIComponent(String(accountId)))
        .replace('{orderId}', encodeURIComponent(String(orderId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List events for an account order.
     * @summary Get Account Order Events
     * @param {string} accountId
     * @param {string} orderId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrdersOrderIdEvents: async (
      accountId: string,
      orderId: string,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrdersOrderIdEvents', 'accountId', accountId);
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrdersOrderIdEvents', 'orderId', orderId);
      const localVarPath = `/api/v1/accounts/{accountId}/orders/{orderId}/events`
        .replace('{accountId}', encodeURIComponent(String(accountId)))
        .replace('{orderId}', encodeURIComponent(String(orderId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List fills for an account order.
     * @summary Get Account Order Fills
     * @param {string} accountId
     * @param {string} orderId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrdersOrderIdFills: async (
      accountId: string,
      orderId: string,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrdersOrderIdFills', 'accountId', accountId);
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdOrdersOrderIdFills', 'orderId', orderId);
      const localVarPath = `/api/v1/accounts/{accountId}/orders/{orderId}/fills`
        .replace('{accountId}', encodeURIComponent(String(accountId)))
        .replace('{orderId}', encodeURIComponent(String(orderId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List account-scoped positions.
     * @summary List Account Positions
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdPositions: async (
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdPositions', 'accountId', accountId);
      const localVarPath = `/api/v1/accounts/{accountId}/positions`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List account-scoped balances, positions, transactions, or orders.
     * @summary List Account Resource
     * @param {string} accountId
     * @param {string} resource
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdResource: async (
      accountId: string,
      resource: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdResource', 'accountId', accountId);
      // verify required parameter 'resource' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdResource', 'resource', resource);
      const localVarPath = `/api/v1/accounts/{accountId}/{resource}`
        .replace('{accountId}', encodeURIComponent(String(accountId)))
        .replace('{resource}', encodeURIComponent(String(resource)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List account-scoped transactions.
     * @summary List Account Transactions
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdTransactions: async (
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1GetAccountsAccountIdTransactions', 'accountId', accountId);
      const localVarPath = `/api/v1/accounts/{accountId}/transactions`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter['offset'] = offset;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Modify an account-scoped order.
     * @summary Modify Account Order
     * @param {string} accountId
     * @param {string} orderId
     * @param {string} idempotencyKey
     * @param {AccountOrderCommandRequest} accountOrderCommandRequest
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PatchAccountsAccountIdOrdersOrderId: async (
      accountId: string,
      orderId: string,
      idempotencyKey: string,
      accountOrderCommandRequest: AccountOrderCommandRequest,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1PatchAccountsAccountIdOrdersOrderId', 'accountId', accountId);
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('finaticV1PatchAccountsAccountIdOrdersOrderId', 'orderId', orderId);
      // verify required parameter 'idempotencyKey' is not null or undefined
      assertParamExists(
        'finaticV1PatchAccountsAccountIdOrdersOrderId',
        'idempotencyKey',
        idempotencyKey
      );
      // verify required parameter 'accountOrderCommandRequest' is not null or undefined
      assertParamExists(
        'finaticV1PatchAccountsAccountIdOrdersOrderId',
        'accountOrderCommandRequest',
        accountOrderCommandRequest
      );
      const localVarPath = `/api/v1/accounts/{accountId}/orders/{orderId}`
        .replace('{accountId}', encodeURIComponent(String(accountId)))
        .replace('{orderId}', encodeURIComponent(String(orderId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      if (idempotencyKey != null) {
        localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
      }
      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        accountOrderCommandRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Create an account-scoped order with grant and idempotency checks.
     * @summary Create Account Order
     * @param {string} accountId
     * @param {string} idempotencyKey
     * @param {AccountOrderCommandRequest} accountOrderCommandRequest
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostAccountsAccountIdOrders: async (
      accountId: string,
      idempotencyKey: string,
      accountOrderCommandRequest: AccountOrderCommandRequest,
      xFinaticEnvironment?: string | null,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'accountId' is not null or undefined
      assertParamExists('finaticV1PostAccountsAccountIdOrders', 'accountId', accountId);
      // verify required parameter 'idempotencyKey' is not null or undefined
      assertParamExists('finaticV1PostAccountsAccountIdOrders', 'idempotencyKey', idempotencyKey);
      // verify required parameter 'accountOrderCommandRequest' is not null or undefined
      assertParamExists(
        'finaticV1PostAccountsAccountIdOrders',
        'accountOrderCommandRequest',
        accountOrderCommandRequest
      );
      const localVarPath = `/api/v1/accounts/{accountId}/orders`.replace(
        '{accountId}',
        encodeURIComponent(String(accountId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      if (idempotencyKey != null) {
        localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
      }
      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        accountOrderCommandRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AccountsApi - functional programming interface
 */
export const AccountsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AccountsApiAxiosParamCreator(configuration);
  return {
    /**
     * Cancel an account-scoped order.
     * @summary Cancel Account Order
     * @param {string} accountId
     * @param {string} orderId
     * @param {string} idempotencyKey
     * @param {string | null} [broker] Optional broker id hint; must match account grant if set.
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1DeleteAccountsAccountIdOrdersOrderId(
      accountId: string,
      orderId: string,
      idempotencyKey: string,
      broker?: string | null,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1DeleteAccountsAccountIdOrdersOrderId(
          accountId,
          orderId,
          idempotencyKey,
          broker,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1DeleteAccountsAccountIdOrdersOrderId']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List broker accounts visible through active account grants.
     * @summary List Accounts
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccounts(
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetAccounts(
        xFinaticEnvironment,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccounts']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get one broker account visible through an active account grant.
     * @summary Get Account
     * @param {string} accountId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountId(
      accountId: string,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrAny>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetAccountsAccountId(
        accountId,
        xFinaticEnvironment,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountId']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List account-scoped balances.
     * @summary List Account Balances
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdBalances(
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdBalances(
          accountId,
          limit,
          offset,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdBalances']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Return JSON Schema for broker-specific order fields for this account.
     * @summary Get Account Order Schema
     * @param {string} accountId
     * @param {string} action Order command action: place, modify, or cancel.
     * @param {string | null} [broker] Optional broker id hint; must match account grant if set.
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdOrderSchemas(
      accountId: string,
      action: string,
      broker?: string | null,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdOrderSchemas(
          accountId,
          action,
          broker,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdOrderSchemas']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List account-scoped orders.
     * @summary List Account Orders
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdOrders(
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdOrders(
        accountId,
        limit,
        offset,
        xFinaticEnvironment,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdOrders']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get one order after account-grant authorization.
     * @summary Get Account Order
     * @param {string} accountId
     * @param {string} orderId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdOrdersOrderId(
      accountId: string,
      orderId: string,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdOrdersOrderId(
          accountId,
          orderId,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdOrdersOrderId']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List events for an account order.
     * @summary Get Account Order Events
     * @param {string} accountId
     * @param {string} orderId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
      accountId: string,
      orderId: string,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
          accountId,
          orderId,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdOrdersOrderIdEvents']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List fills for an account order.
     * @summary Get Account Order Fills
     * @param {string} accountId
     * @param {string} orderId
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdOrdersOrderIdFills(
      accountId: string,
      orderId: string,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdOrdersOrderIdFills(
          accountId,
          orderId,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdOrdersOrderIdFills']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List account-scoped positions.
     * @summary List Account Positions
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdPositions(
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdPositions(
          accountId,
          limit,
          offset,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdPositions']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List account-scoped balances, positions, transactions, or orders.
     * @summary List Account Resource
     * @param {string} accountId
     * @param {string} resource
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdResource(
      accountId: string,
      resource: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdResource(
          accountId,
          resource,
          limit,
          offset,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdResource']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List account-scoped transactions.
     * @summary List Account Transactions
     * @param {string} accountId
     * @param {number} [limit]
     * @param {number} [offset]
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1GetAccountsAccountIdTransactions(
      accountId: string,
      limit?: number,
      offset?: number,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListDictStrAny>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1GetAccountsAccountIdTransactions(
          accountId,
          limit,
          offset,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1GetAccountsAccountIdTransactions']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Modify an account-scoped order.
     * @summary Modify Account Order
     * @param {string} accountId
     * @param {string} orderId
     * @param {string} idempotencyKey
     * @param {AccountOrderCommandRequest} accountOrderCommandRequest
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1PatchAccountsAccountIdOrdersOrderId(
      accountId: string,
      orderId: string,
      idempotencyKey: string,
      accountOrderCommandRequest: AccountOrderCommandRequest,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1PatchAccountsAccountIdOrdersOrderId(
          accountId,
          orderId,
          idempotencyKey,
          accountOrderCommandRequest,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1PatchAccountsAccountIdOrdersOrderId']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Create an account-scoped order with grant and idempotency checks.
     * @summary Create Account Order
     * @param {string} accountId
     * @param {string} idempotencyKey
     * @param {AccountOrderCommandRequest} accountOrderCommandRequest
     * @param {string | null} [xFinaticEnvironment]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1PostAccountsAccountIdOrders(
      accountId: string,
      idempotencyKey: string,
      accountOrderCommandRequest: AccountOrderCommandRequest,
      xFinaticEnvironment?: string | null,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1PostAccountsAccountIdOrders(
          accountId,
          idempotencyKey,
          accountOrderCommandRequest,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AccountsApi.finaticV1PostAccountsAccountIdOrders']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AccountsApi - factory interface
 */
export const AccountsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = AccountsApiFp(configuration);
  return {
    /**
     * Cancel an account-scoped order.
     * @summary Cancel Account Order
     * @param {AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1DeleteAccountsAccountIdOrdersOrderId(
      requestParameters: AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult> {
      return localVarFp
        .finaticV1DeleteAccountsAccountIdOrdersOrderId(
          requestParameters.accountId,
          requestParameters.orderId,
          requestParameters.idempotencyKey,
          requestParameters.broker,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List broker accounts visible through active account grants.
     * @summary List Accounts
     * @param {AccountsApiFinaticV1GetAccountsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccounts(
      requestParameters: AccountsApiFinaticV1GetAccountsRequest = {},
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccounts(requestParameters.xFinaticEnvironment, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get one broker account visible through an active account grant.
     * @summary Get Account
     * @param {AccountsApiFinaticV1GetAccountsAccountIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountId(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountId(
          requestParameters.accountId,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List account-scoped balances.
     * @summary List Account Balances
     * @param {AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdBalances(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdBalances(
          requestParameters.accountId,
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Return JSON Schema for broker-specific order fields for this account.
     * @summary Get Account Order Schema
     * @param {AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrderSchemas(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdOrderSchemas(
          requestParameters.accountId,
          requestParameters.action,
          requestParameters.broker,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List account-scoped orders.
     * @summary List Account Orders
     * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrders(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdOrders(
          requestParameters.accountId,
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Get one order after account-grant authorization.
     * @summary Get Account Order
     * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrdersOrderId(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdOrdersOrderId(
          requestParameters.accountId,
          requestParameters.orderId,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List events for an account order.
     * @summary Get Account Order Events
     * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
          requestParameters.accountId,
          requestParameters.orderId,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List fills for an account order.
     * @summary Get Account Order Fills
     * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdOrdersOrderIdFills(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdOrdersOrderIdFills(
          requestParameters.accountId,
          requestParameters.orderId,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List account-scoped positions.
     * @summary List Account Positions
     * @param {AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdPositions(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdPositions(
          requestParameters.accountId,
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List account-scoped balances, positions, transactions, or orders.
     * @summary List Account Resource
     * @param {AccountsApiFinaticV1GetAccountsAccountIdResourceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdResource(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdResourceRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdResource(
          requestParameters.accountId,
          requestParameters.resource,
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List account-scoped transactions.
     * @summary List Account Transactions
     * @param {AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetAccountsAccountIdTransactions(
      requestParameters: AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseListDictStrAny> {
      return localVarFp
        .finaticV1GetAccountsAccountIdTransactions(
          requestParameters.accountId,
          requestParameters.limit,
          requestParameters.offset,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Modify an account-scoped order.
     * @summary Modify Account Order
     * @param {AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PatchAccountsAccountIdOrdersOrderId(
      requestParameters: AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult> {
      return localVarFp
        .finaticV1PatchAccountsAccountIdOrdersOrderId(
          requestParameters.accountId,
          requestParameters.orderId,
          requestParameters.idempotencyKey,
          requestParameters.accountOrderCommandRequest,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Create an account-scoped order with grant and idempotency checks.
     * @summary Create Account Order
     * @param {AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostAccountsAccountIdOrders(
      requestParameters: AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult> {
      return localVarFp
        .finaticV1PostAccountsAccountIdOrders(
          requestParameters.accountId,
          requestParameters.idempotencyKey,
          requestParameters.accountOrderCommandRequest,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AccountsApi - interface
 */
export interface AccountsApiInterface {
  /**
   * Cancel an account-scoped order.
   * @summary Cancel Account Order
   * @param {AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1DeleteAccountsAccountIdOrdersOrderId(
    requestParameters: AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult>;

  /**
   * List broker accounts visible through active account grants.
   * @summary List Accounts
   * @param {AccountsApiFinaticV1GetAccountsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccounts(
    requestParameters?: AccountsApiFinaticV1GetAccountsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * Get one broker account visible through an active account grant.
   * @summary Get Account
   * @param {AccountsApiFinaticV1GetAccountsAccountIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountId(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseDictStrAny>;

  /**
   * List account-scoped balances.
   * @summary List Account Balances
   * @param {AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdBalances(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * Return JSON Schema for broker-specific order fields for this account.
   * @summary Get Account Order Schema
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdOrderSchemas(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseDictStrAny>;

  /**
   * List account-scoped orders.
   * @summary List Account Orders
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdOrders(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * Get one order after account-grant authorization.
   * @summary Get Account Order
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdOrdersOrderId(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseDictStrAny>;

  /**
   * List events for an account order.
   * @summary Get Account Order Events
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * List fills for an account order.
   * @summary Get Account Order Fills
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdOrdersOrderIdFills(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * List account-scoped positions.
   * @summary List Account Positions
   * @param {AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdPositions(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * List account-scoped balances, positions, transactions, or orders.
   * @summary List Account Resource
   * @param {AccountsApiFinaticV1GetAccountsAccountIdResourceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdResource(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdResourceRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * List account-scoped transactions.
   * @summary List Account Transactions
   * @param {AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1GetAccountsAccountIdTransactions(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseListDictStrAny>;

  /**
   * Modify an account-scoped order.
   * @summary Modify Account Order
   * @param {AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1PatchAccountsAccountIdOrdersOrderId(
    requestParameters: AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult>;

  /**
   * Create an account-scoped order with grant and idempotency checks.
   * @summary Create Account Order
   * @param {AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1PostAccountsAccountIdOrders(
    requestParameters: AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseFDXBrokerOrderCommandResult>;
}

/**
 * Request parameters for finaticV1DeleteAccountsAccountIdOrdersOrderId operation in AccountsApi.
 */
export interface AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest {
  readonly accountId: string;

  readonly orderId: string;

  readonly idempotencyKey: string;

  /**
   * Optional broker id hint; must match account grant if set.
   */
  readonly broker?: string | null;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccounts operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsRequest {
  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountId operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdRequest {
  readonly accountId: string;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdBalances operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest {
  readonly accountId: string;

  readonly limit?: number;

  readonly offset?: number;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdOrderSchemas operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest {
  readonly accountId: string;

  /**
   * Order command action: place, modify, or cancel.
   */
  readonly action: string;

  /**
   * Optional broker id hint; must match account grant if set.
   */
  readonly broker?: string | null;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdOrders operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest {
  readonly accountId: string;

  readonly limit?: number;

  readonly offset?: number;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdOrdersOrderId operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest {
  readonly accountId: string;

  readonly orderId: string;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdOrdersOrderIdEvents operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest {
  readonly accountId: string;

  readonly orderId: string;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdOrdersOrderIdFills operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest {
  readonly accountId: string;

  readonly orderId: string;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdPositions operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest {
  readonly accountId: string;

  readonly limit?: number;

  readonly offset?: number;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdResource operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdResourceRequest {
  readonly accountId: string;

  readonly resource: string;

  readonly limit?: number;

  readonly offset?: number;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1GetAccountsAccountIdTransactions operation in AccountsApi.
 */
export interface AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest {
  readonly accountId: string;

  readonly limit?: number;

  readonly offset?: number;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1PatchAccountsAccountIdOrdersOrderId operation in AccountsApi.
 */
export interface AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest {
  readonly accountId: string;

  readonly orderId: string;

  readonly idempotencyKey: string;

  readonly accountOrderCommandRequest: AccountOrderCommandRequest;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * Request parameters for finaticV1PostAccountsAccountIdOrders operation in AccountsApi.
 */
export interface AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest {
  readonly accountId: string;

  readonly idempotencyKey: string;

  readonly accountOrderCommandRequest: AccountOrderCommandRequest;

  readonly xFinaticEnvironment?: string | null;
}

/**
 * AccountsApi - object-oriented interface
 */
export class AccountsApi extends BaseAPI implements AccountsApiInterface {
  /**
   * Cancel an account-scoped order.
   * @summary Cancel Account Order
   * @param {AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1DeleteAccountsAccountIdOrdersOrderId(
    requestParameters: AccountsApiFinaticV1DeleteAccountsAccountIdOrdersOrderIdRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1DeleteAccountsAccountIdOrdersOrderId(
        requestParameters.accountId,
        requestParameters.orderId,
        requestParameters.idempotencyKey,
        requestParameters.broker,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List broker accounts visible through active account grants.
   * @summary List Accounts
   * @param {AccountsApiFinaticV1GetAccountsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccounts(
    requestParameters: AccountsApiFinaticV1GetAccountsRequest = {},
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccounts(requestParameters.xFinaticEnvironment, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get one broker account visible through an active account grant.
   * @summary Get Account
   * @param {AccountsApiFinaticV1GetAccountsAccountIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountId(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountId(
        requestParameters.accountId,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List account-scoped balances.
   * @summary List Account Balances
   * @param {AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdBalances(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdBalancesRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdBalances(
        requestParameters.accountId,
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Return JSON Schema for broker-specific order fields for this account.
   * @summary Get Account Order Schema
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdOrderSchemas(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrderSchemasRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdOrderSchemas(
        requestParameters.accountId,
        requestParameters.action,
        requestParameters.broker,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List account-scoped orders.
   * @summary List Account Orders
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdOrders(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdOrders(
        requestParameters.accountId,
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get one order after account-grant authorization.
   * @summary Get Account Order
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdOrdersOrderId(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdOrdersOrderId(
        requestParameters.accountId,
        requestParameters.orderId,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List events for an account order.
   * @summary Get Account Order Events
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdEventsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdOrdersOrderIdEvents(
        requestParameters.accountId,
        requestParameters.orderId,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List fills for an account order.
   * @summary Get Account Order Fills
   * @param {AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdOrdersOrderIdFills(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdOrdersOrderIdFillsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdOrdersOrderIdFills(
        requestParameters.accountId,
        requestParameters.orderId,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List account-scoped positions.
   * @summary List Account Positions
   * @param {AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdPositions(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdPositionsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdPositions(
        requestParameters.accountId,
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List account-scoped balances, positions, transactions, or orders.
   * @summary List Account Resource
   * @param {AccountsApiFinaticV1GetAccountsAccountIdResourceRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdResource(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdResourceRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdResource(
        requestParameters.accountId,
        requestParameters.resource,
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List account-scoped transactions.
   * @summary List Account Transactions
   * @param {AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1GetAccountsAccountIdTransactions(
    requestParameters: AccountsApiFinaticV1GetAccountsAccountIdTransactionsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1GetAccountsAccountIdTransactions(
        requestParameters.accountId,
        requestParameters.limit,
        requestParameters.offset,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Modify an account-scoped order.
   * @summary Modify Account Order
   * @param {AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1PatchAccountsAccountIdOrdersOrderId(
    requestParameters: AccountsApiFinaticV1PatchAccountsAccountIdOrdersOrderIdRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1PatchAccountsAccountIdOrdersOrderId(
        requestParameters.accountId,
        requestParameters.orderId,
        requestParameters.idempotencyKey,
        requestParameters.accountOrderCommandRequest,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create an account-scoped order with grant and idempotency checks.
   * @summary Create Account Order
   * @param {AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1PostAccountsAccountIdOrders(
    requestParameters: AccountsApiFinaticV1PostAccountsAccountIdOrdersRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AccountsApiFp(this.configuration)
      .finaticV1PostAccountsAccountIdOrders(
        requestParameters.accountId,
        requestParameters.idempotencyKey,
        requestParameters.accountOrderCommandRequest,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
