/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { BrokerConnectionRequest } from '../models';
// @ts-ignore
import type { FinaticResponseAny } from '../models';
// @ts-ignore
import type { FinaticResponseDictStrStr } from '../models';
// @ts-ignore
import type { FinaticResponseOwnerPortalBootstrapResponse } from '../models';
// @ts-ignore
import type { FinaticResponseOwnerPortalRevokeAllCompaniesResult } from '../models';
// @ts-ignore
import type { FinaticResponseReauthNotificationPreference } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { OwnerPortalCompanyPermissionsUpdate } from '../models';
// @ts-ignore
import type { ReauthNotificationPreferenceUpdateRequest } from '../models';
/**
 * OwnerPortalApi - axios parameter creator
 */
export const OwnerPortalApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Return all user connections and union company directory with per-connection grants.
     * @summary Get Owner Portal Bootstrap
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/owner-portal/bootstrap`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Read reauth email preference for a user-owned connection.
     * @summary Get Owner Reauth Notification Preference
     * @param {string} connectionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet:
      async (connectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
        // verify required parameter 'connectionId' is not null or undefined
        assertParamExists(
          'getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet',
          'connectionId',
          connectionId
        );
        const localVarPath =
          `/api/v1/owner-portal/connections/{connection_id}/reauth-notification-preference`.replace(
            `{${'connection_id'}}`,
            encodeURIComponent(String(connectionId))
          );
        // use dummy base URL string because the URL constructor only accepts absolute URLs.
        const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
        let baseOptions;
        if (configuration) {
          baseOptions = configuration.baseOptions;
        }

        const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
        const localVarHeaderParameter = {} as any;
        const localVarQueryParameter = {} as any;

        // authentication HTTPBearer required
        // http bearer authentication required
        await setBearerAuthToObject(localVarHeaderParameter, configuration);

        setSearchParams(localVarUrlObj, localVarQueryParameter);
        let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
        localVarRequestOptions.headers = {
          ...localVarHeaderParameter,
          ...headersFromBaseOptions,
          ...options.headers,
        };

        return {
          url: toPathString(localVarUrlObj),
          options: localVarRequestOptions,
        };
      },
    /**
     * Connect or reauth a broker without granting company access (personal connection).
     * @summary Owner Portal Connect Broker
     * @param {BrokerConnectionRequest} brokerConnectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost: async (
      brokerConnectionRequest: BrokerConnectionRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'brokerConnectionRequest' is not null or undefined
      assertParamExists(
        'ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost',
        'brokerConnectionRequest',
        brokerConnectionRequest
      );
      const localVarPath = `/api/v1/owner-portal/brokers/connect`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        brokerConnectionRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Disconnect a user-owned broker connection (personal or after revoking company access).
     * @summary Owner Portal Delete Connection
     * @param {string} connectionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete: async (
      connectionId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'connectionId' is not null or undefined
      assertParamExists(
        'ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete',
        'connectionId',
        connectionId
      );
      const localVarPath = `/api/v1/owner-portal/connections/{connection_id}`.replace(
        `{${'connection_id'}}`,
        encodeURIComponent(String(connectionId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Remove every company_access row for a connection.
     * @summary Revoke All Owner Connection Company Access
     * @param {string} connectionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete:
      async (connectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
        // verify required parameter 'connectionId' is not null or undefined
        assertParamExists(
          'revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete',
          'connectionId',
          connectionId
        );
        const localVarPath = `/api/v1/owner-portal/connections/{connection_id}/companies`.replace(
          `{${'connection_id'}}`,
          encodeURIComponent(String(connectionId))
        );
        // use dummy base URL string because the URL constructor only accepts absolute URLs.
        const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
        let baseOptions;
        if (configuration) {
          baseOptions = configuration.baseOptions;
        }

        const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
        const localVarHeaderParameter = {} as any;
        const localVarQueryParameter = {} as any;

        // authentication HTTPBearer required
        // http bearer authentication required
        await setBearerAuthToObject(localVarHeaderParameter, configuration);

        setSearchParams(localVarUrlObj, localVarQueryParameter);
        let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
        localVarRequestOptions.headers = {
          ...localVarHeaderParameter,
          ...headersFromBaseOptions,
          ...options.headers,
        };

        return {
          url: toPathString(localVarUrlObj),
          options: localVarRequestOptions,
        };
      },
    /**
     * Remove one company\'s access to a connection.
     * @summary Revoke Owner Connection Company Access
     * @param {string} connectionId
     * @param {string} companyId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete:
      async (
        connectionId: string,
        companyId: string,
        options: RawAxiosRequestConfig = {}
      ): Promise<RequestArgs> => {
        // verify required parameter 'connectionId' is not null or undefined
        assertParamExists(
          'revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete',
          'connectionId',
          connectionId
        );
        // verify required parameter 'companyId' is not null or undefined
        assertParamExists(
          'revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete',
          'companyId',
          companyId
        );
        const localVarPath =
          `/api/v1/owner-portal/connections/{connection_id}/companies/{company_id}`
            .replace(`{${'connection_id'}}`, encodeURIComponent(String(connectionId)))
            .replace(`{${'company_id'}}`, encodeURIComponent(String(companyId)));
        // use dummy base URL string because the URL constructor only accepts absolute URLs.
        const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
        let baseOptions;
        if (configuration) {
          baseOptions = configuration.baseOptions;
        }

        const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
        const localVarHeaderParameter = {} as any;
        const localVarQueryParameter = {} as any;

        // authentication HTTPBearer required
        // http bearer authentication required
        await setBearerAuthToObject(localVarHeaderParameter, configuration);

        setSearchParams(localVarUrlObj, localVarQueryParameter);
        let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
        localVarRequestOptions.headers = {
          ...localVarHeaderParameter,
          ...headersFromBaseOptions,
          ...options.headers,
        };

        return {
          url: toPathString(localVarUrlObj),
          options: localVarRequestOptions,
        };
      },
    /**
     * Create or update company_access for one company on a user-owned connection.
     * @summary Update Owner Connection Company Permissions
     * @param {string} connectionId
     * @param {string} companyId
     * @param {OwnerPortalCompanyPermissionsUpdate} ownerPortalCompanyPermissionsUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch:
      async (
        connectionId: string,
        companyId: string,
        ownerPortalCompanyPermissionsUpdate: OwnerPortalCompanyPermissionsUpdate,
        options: RawAxiosRequestConfig = {}
      ): Promise<RequestArgs> => {
        // verify required parameter 'connectionId' is not null or undefined
        assertParamExists(
          'updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch',
          'connectionId',
          connectionId
        );
        // verify required parameter 'companyId' is not null or undefined
        assertParamExists(
          'updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch',
          'companyId',
          companyId
        );
        // verify required parameter 'ownerPortalCompanyPermissionsUpdate' is not null or undefined
        assertParamExists(
          'updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch',
          'ownerPortalCompanyPermissionsUpdate',
          ownerPortalCompanyPermissionsUpdate
        );
        const localVarPath =
          `/api/v1/owner-portal/connections/{connection_id}/companies/{company_id}/permissions`
            .replace(`{${'connection_id'}}`, encodeURIComponent(String(connectionId)))
            .replace(`{${'company_id'}}`, encodeURIComponent(String(companyId)));
        // use dummy base URL string because the URL constructor only accepts absolute URLs.
        const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
        let baseOptions;
        if (configuration) {
          baseOptions = configuration.baseOptions;
        }

        const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
        const localVarHeaderParameter = {} as any;
        const localVarQueryParameter = {} as any;

        // authentication HTTPBearer required
        // http bearer authentication required
        await setBearerAuthToObject(localVarHeaderParameter, configuration);

        localVarHeaderParameter['Content-Type'] = 'application/json';

        setSearchParams(localVarUrlObj, localVarQueryParameter);
        let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
        localVarRequestOptions.headers = {
          ...localVarHeaderParameter,
          ...headersFromBaseOptions,
          ...options.headers,
        };
        localVarRequestOptions.data = serializeDataIfNeeded(
          ownerPortalCompanyPermissionsUpdate,
          localVarRequestOptions,
          configuration
        );

        return {
          url: toPathString(localVarUrlObj),
          options: localVarRequestOptions,
        };
      },
    /**
     * Persist reauth email preference for a user-owned connection.
     * @summary Update Owner Reauth Notification Preference
     * @param {string} connectionId
     * @param {ReauthNotificationPreferenceUpdateRequest} reauthNotificationPreferenceUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch:
      async (
        connectionId: string,
        reauthNotificationPreferenceUpdateRequest: ReauthNotificationPreferenceUpdateRequest,
        options: RawAxiosRequestConfig = {}
      ): Promise<RequestArgs> => {
        // verify required parameter 'connectionId' is not null or undefined
        assertParamExists(
          'updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch',
          'connectionId',
          connectionId
        );
        // verify required parameter 'reauthNotificationPreferenceUpdateRequest' is not null or undefined
        assertParamExists(
          'updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch',
          'reauthNotificationPreferenceUpdateRequest',
          reauthNotificationPreferenceUpdateRequest
        );
        const localVarPath =
          `/api/v1/owner-portal/connections/{connection_id}/reauth-notification-preference`.replace(
            `{${'connection_id'}}`,
            encodeURIComponent(String(connectionId))
          );
        // use dummy base URL string because the URL constructor only accepts absolute URLs.
        const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
        let baseOptions;
        if (configuration) {
          baseOptions = configuration.baseOptions;
        }

        const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
        const localVarHeaderParameter = {} as any;
        const localVarQueryParameter = {} as any;

        // authentication HTTPBearer required
        // http bearer authentication required
        await setBearerAuthToObject(localVarHeaderParameter, configuration);

        localVarHeaderParameter['Content-Type'] = 'application/json';

        setSearchParams(localVarUrlObj, localVarQueryParameter);
        let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
        localVarRequestOptions.headers = {
          ...localVarHeaderParameter,
          ...headersFromBaseOptions,
          ...options.headers,
        };
        localVarRequestOptions.data = serializeDataIfNeeded(
          reauthNotificationPreferenceUpdateRequest,
          localVarRequestOptions,
          configuration
        );

        return {
          url: toPathString(localVarUrlObj),
          options: localVarRequestOptions,
        };
      },
  };
};

/**
 * OwnerPortalApi - functional programming interface
 */
export const OwnerPortalApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = OwnerPortalApiAxiosParamCreator(configuration);
  return {
    /**
     * Return all user connections and union company directory with per-connection grants.
     * @summary Get Owner Portal Bootstrap
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseOwnerPortalBootstrapResponse>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['OwnerPortalApi.getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Read reauth email preference for a user-owned connection.
     * @summary Get Owner Reauth Notification Preference
     * @param {string} connectionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
      connectionId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseReauthNotificationPreference>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
          connectionId,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Connect or reauth a broker without granting company access (personal connection).
     * @summary Owner Portal Connect Broker
     * @param {BrokerConnectionRequest} brokerConnectionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
      brokerConnectionRequest: BrokerConnectionRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseAny>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
          brokerConnectionRequest,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Disconnect a user-owned broker connection (personal or after revoking company access).
     * @summary Owner Portal Delete Connection
     * @param {string} connectionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
      connectionId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseOwnerPortalRevokeAllCompaniesResult>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
          connectionId,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Remove every company_access row for a connection.
     * @summary Revoke All Owner Connection Company Access
     * @param {string} connectionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
      connectionId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseOwnerPortalRevokeAllCompaniesResult>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
          connectionId,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Remove one company\'s access to a connection.
     * @summary Revoke Owner Connection Company Access
     * @param {string} connectionId
     * @param {string} companyId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
      connectionId: string,
      companyId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrStr>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
          connectionId,
          companyId,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Create or update company_access for one company on a user-owned connection.
     * @summary Update Owner Connection Company Permissions
     * @param {string} connectionId
     * @param {string} companyId
     * @param {OwnerPortalCompanyPermissionsUpdate} ownerPortalCompanyPermissionsUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
      connectionId: string,
      companyId: string,
      ownerPortalCompanyPermissionsUpdate: OwnerPortalCompanyPermissionsUpdate,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrStr>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
          connectionId,
          companyId,
          ownerPortalCompanyPermissionsUpdate,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Persist reauth email preference for a user-owned connection.
     * @summary Update Owner Reauth Notification Preference
     * @param {string} connectionId
     * @param {ReauthNotificationPreferenceUpdateRequest} reauthNotificationPreferenceUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
      connectionId: string,
      reauthNotificationPreferenceUpdateRequest: ReauthNotificationPreferenceUpdateRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseReauthNotificationPreference>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
          connectionId,
          reauthNotificationPreferenceUpdateRequest,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          'OwnerPortalApi.updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch'
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * OwnerPortalApi - factory interface
 */
export const OwnerPortalApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = OwnerPortalApiFp(configuration);
  return {
    /**
     * Return all user connections and union company directory with per-connection grants.
     * @summary Get Owner Portal Bootstrap
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseOwnerPortalBootstrapResponse> {
      return localVarFp
        .getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Read reauth email preference for a user-owned connection.
     * @summary Get Owner Reauth Notification Preference
     * @param {OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
      requestParameters: OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseReauthNotificationPreference> {
      return localVarFp
        .getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
          requestParameters.connectionId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Connect or reauth a broker without granting company access (personal connection).
     * @summary Owner Portal Connect Broker
     * @param {OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
      requestParameters: OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseAny> {
      return localVarFp
        .ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
          requestParameters.brokerConnectionRequest,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Disconnect a user-owned broker connection (personal or after revoking company access).
     * @summary Owner Portal Delete Connection
     * @param {OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
      requestParameters: OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseOwnerPortalRevokeAllCompaniesResult> {
      return localVarFp
        .ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
          requestParameters.connectionId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Remove every company_access row for a connection.
     * @summary Revoke All Owner Connection Company Access
     * @param {OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
      requestParameters: OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseOwnerPortalRevokeAllCompaniesResult> {
      return localVarFp
        .revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
          requestParameters.connectionId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Remove one company\'s access to a connection.
     * @summary Revoke Owner Connection Company Access
     * @param {OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
      requestParameters: OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseDictStrStr> {
      return localVarFp
        .revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
          requestParameters.connectionId,
          requestParameters.companyId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Create or update company_access for one company on a user-owned connection.
     * @summary Update Owner Connection Company Permissions
     * @param {OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
      requestParameters: OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseDictStrStr> {
      return localVarFp
        .updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
          requestParameters.connectionId,
          requestParameters.companyId,
          requestParameters.ownerPortalCompanyPermissionsUpdate,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Persist reauth email preference for a user-owned connection.
     * @summary Update Owner Reauth Notification Preference
     * @param {OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
      requestParameters: OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseReauthNotificationPreference> {
      return localVarFp
        .updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
          requestParameters.connectionId,
          requestParameters.reauthNotificationPreferenceUpdateRequest,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * OwnerPortalApi - interface
 */
export interface OwnerPortalApiInterface {
  /**
   * Return all user connections and union company directory with per-connection grants.
   * @summary Get Owner Portal Bootstrap
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseOwnerPortalBootstrapResponse>;

  /**
   * Read reauth email preference for a user-owned connection.
   * @summary Get Owner Reauth Notification Preference
   * @param {OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
    requestParameters: OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseReauthNotificationPreference>;

  /**
   * Connect or reauth a broker without granting company access (personal connection).
   * @summary Owner Portal Connect Broker
   * @param {OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
    requestParameters: OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseAny>;

  /**
   * Disconnect a user-owned broker connection (personal or after revoking company access).
   * @summary Owner Portal Delete Connection
   * @param {OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
    requestParameters: OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseOwnerPortalRevokeAllCompaniesResult>;

  /**
   * Remove every company_access row for a connection.
   * @summary Revoke All Owner Connection Company Access
   * @param {OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
    requestParameters: OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseOwnerPortalRevokeAllCompaniesResult>;

  /**
   * Remove one company\'s access to a connection.
   * @summary Revoke Owner Connection Company Access
   * @param {OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
    requestParameters: OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseDictStrStr>;

  /**
   * Create or update company_access for one company on a user-owned connection.
   * @summary Update Owner Connection Company Permissions
   * @param {OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
    requestParameters: OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseDictStrStr>;

  /**
   * Persist reauth email preference for a user-owned connection.
   * @summary Update Owner Reauth Notification Preference
   * @param {OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
    requestParameters: OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseReauthNotificationPreference>;
}

/**
 * Request parameters for getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet operation in OwnerPortalApi.
 */
export interface OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest {
  readonly connectionId: string;
}

/**
 * Request parameters for ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost operation in OwnerPortalApi.
 */
export interface OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest {
  readonly brokerConnectionRequest: BrokerConnectionRequest;
}

/**
 * Request parameters for ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete operation in OwnerPortalApi.
 */
export interface OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest {
  readonly connectionId: string;
}

/**
 * Request parameters for revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete operation in OwnerPortalApi.
 */
export interface OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest {
  readonly connectionId: string;
}

/**
 * Request parameters for revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete operation in OwnerPortalApi.
 */
export interface OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest {
  readonly connectionId: string;

  readonly companyId: string;
}

/**
 * Request parameters for updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch operation in OwnerPortalApi.
 */
export interface OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest {
  readonly connectionId: string;

  readonly companyId: string;

  readonly ownerPortalCompanyPermissionsUpdate: OwnerPortalCompanyPermissionsUpdate;
}

/**
 * Request parameters for updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch operation in OwnerPortalApi.
 */
export interface OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest {
  readonly connectionId: string;

  readonly reauthNotificationPreferenceUpdateRequest: ReauthNotificationPreferenceUpdateRequest;
}

/**
 * OwnerPortalApi - object-oriented interface
 */
export class OwnerPortalApi extends BaseAPI implements OwnerPortalApiInterface {
  /**
   * Return all user connections and union company directory with per-connection grants.
   * @summary Get Owner Portal Bootstrap
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(options?: RawAxiosRequestConfig) {
    return OwnerPortalApiFp(this.configuration)
      .getOwnerPortalBootstrapApiV1OwnerPortalBootstrapGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Read reauth email preference for a user-owned connection.
   * @summary Get Owner Reauth Notification Preference
   * @param {OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
    requestParameters: OwnerPortalApiGetOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGetRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .getOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferenceGet(
        requestParameters.connectionId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Connect or reauth a broker without granting company access (personal connection).
   * @summary Owner Portal Connect Broker
   * @param {OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
    requestParameters: OwnerPortalApiOwnerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPostRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .ownerPortalConnectBrokerApiV1OwnerPortalBrokersConnectPost(
        requestParameters.brokerConnectionRequest,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Disconnect a user-owned broker connection (personal or after revoking company access).
   * @summary Owner Portal Delete Connection
   * @param {OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
    requestParameters: OwnerPortalApiOwnerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDeleteRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .ownerPortalDeleteConnectionApiV1OwnerPortalConnectionsConnectionIdDelete(
        requestParameters.connectionId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Remove every company_access row for a connection.
   * @summary Revoke All Owner Connection Company Access
   * @param {OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
    requestParameters: OwnerPortalApiRevokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDeleteRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .revokeAllOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesDelete(
        requestParameters.connectionId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Remove one company\'s access to a connection.
   * @summary Revoke Owner Connection Company Access
   * @param {OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
    requestParameters: OwnerPortalApiRevokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDeleteRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .revokeOwnerConnectionCompanyAccessApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdDelete(
        requestParameters.connectionId,
        requestParameters.companyId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Create or update company_access for one company on a user-owned connection.
   * @summary Update Owner Connection Company Permissions
   * @param {OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
    requestParameters: OwnerPortalApiUpdateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatchRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .updateOwnerConnectionCompanyPermissionsApiV1OwnerPortalConnectionsConnectionIdCompaniesCompanyIdPermissionsPatch(
        requestParameters.connectionId,
        requestParameters.companyId,
        requestParameters.ownerPortalCompanyPermissionsUpdate,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Persist reauth email preference for a user-owned connection.
   * @summary Update Owner Reauth Notification Preference
   * @param {OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
    requestParameters: OwnerPortalApiUpdateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatchRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OwnerPortalApiFp(this.configuration)
      .updateOwnerReauthNotificationPreferenceApiV1OwnerPortalConnectionsConnectionIdReauthNotificationPreferencePatch(
        requestParameters.connectionId,
        requestParameters.reauthNotificationPreferenceUpdateRequest,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
