/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import type { FinaticEnvironment } from '../models';
// @ts-ignore
import type { FinaticResponseReauthNotificationOptOutResult } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { ReauthNotificationOptOutRequest } from '../models';
/**
 * PortalApi - axios parameter creator
 */
export const PortalApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Apply an email opt-out token through the API service boundary.
     * @summary Apply Reauth Notification Opt Out
     * @param {ReauthNotificationOptOutRequest} reauthNotificationOptOutRequest
     * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostPortalReauthNotificationOptOut: async (
      reauthNotificationOptOutRequest: ReauthNotificationOptOutRequest,
      xFinaticEnvironment?: FinaticEnvironment,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'reauthNotificationOptOutRequest' is not null or undefined
      assertParamExists(
        'finaticV1PostPortalReauthNotificationOptOut',
        'reauthNotificationOptOutRequest',
        reauthNotificationOptOutRequest
      );
      const localVarPath = `/api/v1/portal/reauth-notification-opt-out`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      if (xFinaticEnvironment != null) {
        localVarHeaderParameter['X-Finatic-Environment'] =
          typeof xFinaticEnvironment === 'string'
            ? xFinaticEnvironment
            : JSON.stringify(xFinaticEnvironment, replaceWithSerializableTypeIfNeeded);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        reauthNotificationOptOutRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PortalApi - functional programming interface
 */
export const PortalApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PortalApiAxiosParamCreator(configuration);
  return {
    /**
     * Apply an email opt-out token through the API service boundary.
     * @summary Apply Reauth Notification Opt Out
     * @param {ReauthNotificationOptOutRequest} reauthNotificationOptOutRequest
     * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async finaticV1PostPortalReauthNotificationOptOut(
      reauthNotificationOptOutRequest: ReauthNotificationOptOutRequest,
      xFinaticEnvironment?: FinaticEnvironment,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<FinaticResponseReauthNotificationOptOutResult>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.finaticV1PostPortalReauthNotificationOptOut(
          reauthNotificationOptOutRequest,
          xFinaticEnvironment,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['PortalApi.finaticV1PostPortalReauthNotificationOptOut']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * PortalApi - factory interface
 */
export const PortalApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = PortalApiFp(configuration);
  return {
    /**
     * Apply an email opt-out token through the API service boundary.
     * @summary Apply Reauth Notification Opt Out
     * @param {PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostPortalReauthNotificationOptOut(
      requestParameters: PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<FinaticResponseReauthNotificationOptOutResult> {
      return localVarFp
        .finaticV1PostPortalReauthNotificationOptOut(
          requestParameters.reauthNotificationOptOutRequest,
          requestParameters.xFinaticEnvironment,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PortalApi - interface
 */
export interface PortalApiInterface {
  /**
   * Apply an email opt-out token through the API service boundary.
   * @summary Apply Reauth Notification Opt Out
   * @param {PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  finaticV1PostPortalReauthNotificationOptOut(
    requestParameters: PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<FinaticResponseReauthNotificationOptOutResult>;
}

/**
 * Request parameters for finaticV1PostPortalReauthNotificationOptOut operation in PortalApi.
 */
export interface PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest {
  readonly reauthNotificationOptOutRequest: ReauthNotificationOptOutRequest;

  /**
   * Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
   */
  readonly xFinaticEnvironment?: FinaticEnvironment;
}

/**
 * PortalApi - object-oriented interface
 */
export class PortalApi extends BaseAPI implements PortalApiInterface {
  /**
   * Apply an email opt-out token through the API service boundary.
   * @summary Apply Reauth Notification Opt Out
   * @param {PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public finaticV1PostPortalReauthNotificationOptOut(
    requestParameters: PortalApiFinaticV1PostPortalReauthNotificationOptOutRequest,
    options?: RawAxiosRequestConfig
  ) {
    return PortalApiFp(this.configuration)
      .finaticV1PostPortalReauthNotificationOptOut(
        requestParameters.reauthNotificationOptOutRequest,
        requestParameters.xFinaticEnvironment,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
