/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FinaticAPIErrorResponse } from '../models';
// @ts-ignore
import type { FinaticResponsePortalUrlResponse } from '../models';
// @ts-ignore
import type { FinaticResponseSessionResponseData } from '../models';
// @ts-ignore
import type { FinaticResponseSessionUserResponse } from '../models';
// @ts-ignore
import type { FinaticResponseTokenResponseData } from '../models';
// @ts-ignore
import type { SessionStartRequest } from '../models';
/**
 * SessionApi - axios parameter creator
 */
export const SessionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
         * @summary Get Portal Url
         * @param {string} sessionId Session ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPortalUrlApiV1SessionPortalGet: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getPortalUrlApiV1SessionPortalGet', 'sessionId', sessionId)
            const localVarPath = `/api/v1/session/portal`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (sessionId != null) {
                localVarHeaderParameter['session-id'] = String(sessionId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
         * @summary Get Session User
         * @param {string} sessionId Session ID
         * @param {string} xSessionId Session ID from header (must match path parameter)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionUserApiV1SessionSessionIdUserGet: async (sessionId: string, xSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getSessionUserApiV1SessionSessionIdUserGet', 'sessionId', sessionId)
            // verify required parameter 'xSessionId' is not null or undefined
            assertParamExists('getSessionUserApiV1SessionSessionIdUserGet', 'xSessionId', xSessionId)
            const localVarPath = `/api/v1/session/{session_id}/user`
                .replace('{session_id}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xSessionId != null) {
                localVarHeaderParameter['x-session-id'] = String(xSessionId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initialize a new session with company API key.
         * @summary Init Session
         * @param {string} xApiKey Company API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        initSessionApiV1SessionInitPost: async (xApiKey: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('initSessionApiV1SessionInitPost', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/session/init`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start a session with a one-time token.
         * @summary Start Session
         * @param {string} oneTimeToken One-time use token obtained from init_session endpoint to authenticate and start the session
         * @param {SessionStartRequest | null} [sessionStartRequest] Session start request containing optional user ID to associate with the session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startSessionApiV1SessionStartPost: async (oneTimeToken: string, sessionStartRequest?: SessionStartRequest | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'oneTimeToken' is not null or undefined
            assertParamExists('startSessionApiV1SessionStartPost', 'oneTimeToken', oneTimeToken)
            const localVarPath = `/api/v1/session/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (oneTimeToken != null) {
                localVarHeaderParameter['One-Time-Token'] = String(oneTimeToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sessionStartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionApi - functional programming interface
 */
export const SessionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
         * @summary Get Portal Url
         * @param {string} sessionId Session ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPortalUrlApiV1SessionPortalGet(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponsePortalUrlResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPortalUrlApiV1SessionPortalGet(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.getPortalUrlApiV1SessionPortalGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
         * @summary Get Session User
         * @param {string} sessionId Session ID
         * @param {string} xSessionId Session ID from header (must match path parameter)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSessionUserApiV1SessionSessionIdUserGet(sessionId: string, xSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseSessionUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSessionUserApiV1SessionSessionIdUserGet(sessionId, xSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.getSessionUserApiV1SessionSessionIdUserGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Initialize a new session with company API key.
         * @summary Init Session
         * @param {string} xApiKey Company API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async initSessionApiV1SessionInitPost(xApiKey: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseTokenResponseData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.initSessionApiV1SessionInitPost(xApiKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.initSessionApiV1SessionInitPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Start a session with a one-time token.
         * @summary Start Session
         * @param {string} oneTimeToken One-time use token obtained from init_session endpoint to authenticate and start the session
         * @param {SessionStartRequest | null} [sessionStartRequest] Session start request containing optional user ID to associate with the session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startSessionApiV1SessionStartPost(oneTimeToken: string, sessionStartRequest?: SessionStartRequest | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseSessionResponseData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startSessionApiV1SessionStartPost(oneTimeToken, sessionStartRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.startSessionApiV1SessionStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SessionApi - factory interface
 */
export const SessionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionApiFp(configuration)
    return {
        /**
         * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
         * @summary Get Portal Url
         * @param {SessionApiGetPortalUrlApiV1SessionPortalGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPortalUrlApiV1SessionPortalGet(requestParameters: SessionApiGetPortalUrlApiV1SessionPortalGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponsePortalUrlResponse> {
            return localVarFp.getPortalUrlApiV1SessionPortalGet(requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
         * @summary Get Session User
         * @param {SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionUserApiV1SessionSessionIdUserGet(requestParameters: SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionUserResponse> {
            return localVarFp.getSessionUserApiV1SessionSessionIdUserGet(requestParameters.sessionId, requestParameters.xSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Initialize a new session with company API key.
         * @summary Init Session
         * @param {SessionApiInitSessionApiV1SessionInitPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        initSessionApiV1SessionInitPost(requestParameters: SessionApiInitSessionApiV1SessionInitPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseTokenResponseData> {
            return localVarFp.initSessionApiV1SessionInitPost(requestParameters.xApiKey, options).then((request) => request(axios, basePath));
        },
        /**
         * Start a session with a one-time token.
         * @summary Start Session
         * @param {SessionApiStartSessionApiV1SessionStartPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startSessionApiV1SessionStartPost(requestParameters: SessionApiStartSessionApiV1SessionStartPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionResponseData> {
            return localVarFp.startSessionApiV1SessionStartPost(requestParameters.oneTimeToken, requestParameters.sessionStartRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SessionApi - interface
 */
export interface SessionApiInterface {
    /**
     * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
     * @summary Get Portal Url
     * @param {SessionApiGetPortalUrlApiV1SessionPortalGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortalUrlApiV1SessionPortalGet(requestParameters: SessionApiGetPortalUrlApiV1SessionPortalGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponsePortalUrlResponse>;

    /**
     * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
     * @summary Get Session User
     * @param {SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSessionUserApiV1SessionSessionIdUserGet(requestParameters: SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionUserResponse>;

    /**
     * Initialize a new session with company API key.
     * @summary Init Session
     * @param {SessionApiInitSessionApiV1SessionInitPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    initSessionApiV1SessionInitPost(requestParameters: SessionApiInitSessionApiV1SessionInitPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseTokenResponseData>;

    /**
     * Start a session with a one-time token.
     * @summary Start Session
     * @param {SessionApiStartSessionApiV1SessionStartPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startSessionApiV1SessionStartPost(requestParameters: SessionApiStartSessionApiV1SessionStartPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionResponseData>;

}

/**
 * Request parameters for getPortalUrlApiV1SessionPortalGet operation in SessionApi.
 */
export interface SessionApiGetPortalUrlApiV1SessionPortalGetRequest {
    /**
     * Session ID
     */
    readonly sessionId: string
}

/**
 * Request parameters for getSessionUserApiV1SessionSessionIdUserGet operation in SessionApi.
 */
export interface SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest {
    /**
     * Session ID
     */
    readonly sessionId: string

    /**
     * Session ID from header (must match path parameter)
     */
    readonly xSessionId: string
}

/**
 * Request parameters for initSessionApiV1SessionInitPost operation in SessionApi.
 */
export interface SessionApiInitSessionApiV1SessionInitPostRequest {
    /**
     * Company API key
     */
    readonly xApiKey: string
}

/**
 * Request parameters for startSessionApiV1SessionStartPost operation in SessionApi.
 */
export interface SessionApiStartSessionApiV1SessionStartPostRequest {
    /**
     * One-time use token obtained from init_session endpoint to authenticate and start the session
     */
    readonly oneTimeToken: string

    /**
     * Session start request containing optional user ID to associate with the session
     */
    readonly sessionStartRequest?: SessionStartRequest | null
}

/**
 * SessionApi - object-oriented interface
 */
export class SessionApi extends BaseAPI implements SessionApiInterface {
    /**
     * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
     * @summary Get Portal Url
     * @param {SessionApiGetPortalUrlApiV1SessionPortalGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPortalUrlApiV1SessionPortalGet(requestParameters: SessionApiGetPortalUrlApiV1SessionPortalGetRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).getPortalUrlApiV1SessionPortalGet(requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
     * @summary Get Session User
     * @param {SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSessionUserApiV1SessionSessionIdUserGet(requestParameters: SessionApiGetSessionUserApiV1SessionSessionIdUserGetRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).getSessionUserApiV1SessionSessionIdUserGet(requestParameters.sessionId, requestParameters.xSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initialize a new session with company API key.
     * @summary Init Session
     * @param {SessionApiInitSessionApiV1SessionInitPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public initSessionApiV1SessionInitPost(requestParameters: SessionApiInitSessionApiV1SessionInitPostRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).initSessionApiV1SessionInitPost(requestParameters.xApiKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start a session with a one-time token.
     * @summary Start Session
     * @param {SessionApiStartSessionApiV1SessionStartPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public startSessionApiV1SessionStartPost(requestParameters: SessionApiStartSessionApiV1SessionStartPostRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).startSessionApiV1SessionStartPost(requestParameters.oneTimeToken, requestParameters.sessionStartRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

