/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FinaticAPIErrorResponse } from '../models';
// @ts-ignore
import type { FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponsePortalUrlResponse2 } from '../models';
// @ts-ignore
import type { FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData2 } from '../models';
// @ts-ignore
import type { FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionUserResponse2 } from '../models';
// @ts-ignore
import type { FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData2 } from '../models';
// @ts-ignore
import type { SessionStartRequest } from '../models';
/**
 * SessionApi - axios parameter creator
 */
export const SessionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
         * @summary Get Portal Url
         * @param {string} sessionId Session ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPortalUrlApiBetaSessionPortalGet: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getPortalUrlApiBetaSessionPortalGet', 'sessionId', sessionId)
            const localVarPath = `/api/beta/session/portal`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (sessionId != null) {
                localVarHeaderParameter['session-id'] = String(sessionId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
         * @summary Get Session User
         * @param {string} sessionId Session ID
         * @param {string} xSessionId Session ID from header (must match path parameter)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionUserApiBetaSessionSessionIdUserGet: async (sessionId: string, xSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getSessionUserApiBetaSessionSessionIdUserGet', 'sessionId', sessionId)
            // verify required parameter 'xSessionId' is not null or undefined
            assertParamExists('getSessionUserApiBetaSessionSessionIdUserGet', 'xSessionId', xSessionId)
            const localVarPath = `/api/beta/session/{session_id}/user`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xSessionId != null) {
                localVarHeaderParameter['x-session-id'] = String(xSessionId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initialize a new session with company API key.
         * @summary Init Session
         * @param {string} xApiKey Company API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        initSessionApiBetaSessionInitPost: async (xApiKey: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('initSessionApiBetaSessionInitPost', 'xApiKey', xApiKey)
            const localVarPath = `/api/beta/session/init`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start a session with a one-time token.
         * @summary Start Session
         * @param {string} oneTimeToken One-time use token obtained from init_session endpoint to authenticate and start the session
         * @param {SessionStartRequest} sessionStartRequest Session start request containing optional user ID to associate with the session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startSessionApiBetaSessionStartPost: async (oneTimeToken: string, sessionStartRequest: SessionStartRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'oneTimeToken' is not null or undefined
            assertParamExists('startSessionApiBetaSessionStartPost', 'oneTimeToken', oneTimeToken)
            // verify required parameter 'sessionStartRequest' is not null or undefined
            assertParamExists('startSessionApiBetaSessionStartPost', 'sessionStartRequest', sessionStartRequest)
            const localVarPath = `/api/beta/session/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (oneTimeToken != null) {
                localVarHeaderParameter['One-Time-Token'] = String(oneTimeToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sessionStartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionApi - functional programming interface
 */
export const SessionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
         * @summary Get Portal Url
         * @param {string} sessionId Session ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPortalUrlApiBetaSessionPortalGet(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponsePortalUrlResponse2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPortalUrlApiBetaSessionPortalGet(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.getPortalUrlApiBetaSessionPortalGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
         * @summary Get Session User
         * @param {string} sessionId Session ID
         * @param {string} xSessionId Session ID from header (must match path parameter)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSessionUserApiBetaSessionSessionIdUserGet(sessionId: string, xSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionUserResponse2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSessionUserApiBetaSessionSessionIdUserGet(sessionId, xSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.getSessionUserApiBetaSessionSessionIdUserGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Initialize a new session with company API key.
         * @summary Init Session
         * @param {string} xApiKey Company API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async initSessionApiBetaSessionInitPost(xApiKey: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.initSessionApiBetaSessionInitPost(xApiKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.initSessionApiBetaSessionInitPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Start a session with a one-time token.
         * @summary Start Session
         * @param {string} oneTimeToken One-time use token obtained from init_session endpoint to authenticate and start the session
         * @param {SessionStartRequest} sessionStartRequest Session start request containing optional user ID to associate with the session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startSessionApiBetaSessionStartPost(oneTimeToken: string, sessionStartRequest: SessionStartRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startSessionApiBetaSessionStartPost(oneTimeToken, sessionStartRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionApi.startSessionApiBetaSessionStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SessionApi - factory interface
 */
export const SessionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionApiFp(configuration)
    return {
        /**
         * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
         * @summary Get Portal Url
         * @param {SessionApiGetPortalUrlApiBetaSessionPortalGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPortalUrlApiBetaSessionPortalGet(requestParameters: SessionApiGetPortalUrlApiBetaSessionPortalGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponsePortalUrlResponse2> {
            return localVarFp.getPortalUrlApiBetaSessionPortalGet(requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
         * @summary Get Session User
         * @param {SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionUserApiBetaSessionSessionIdUserGet(requestParameters: SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionUserResponse2> {
            return localVarFp.getSessionUserApiBetaSessionSessionIdUserGet(requestParameters.sessionId, requestParameters.xSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Initialize a new session with company API key.
         * @summary Init Session
         * @param {SessionApiInitSessionApiBetaSessionInitPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        initSessionApiBetaSessionInitPost(requestParameters: SessionApiInitSessionApiBetaSessionInitPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData2> {
            return localVarFp.initSessionApiBetaSessionInitPost(requestParameters.xApiKey, options).then((request) => request(axios, basePath));
        },
        /**
         * Start a session with a one-time token.
         * @summary Start Session
         * @param {SessionApiStartSessionApiBetaSessionStartPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startSessionApiBetaSessionStartPost(requestParameters: SessionApiStartSessionApiBetaSessionStartPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData2> {
            return localVarFp.startSessionApiBetaSessionStartPost(requestParameters.oneTimeToken, requestParameters.sessionStartRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SessionApi - interface
 */
export interface SessionApiInterface {
    /**
     * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
     * @summary Get Portal Url
     * @param {SessionApiGetPortalUrlApiBetaSessionPortalGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPortalUrlApiBetaSessionPortalGet(requestParameters: SessionApiGetPortalUrlApiBetaSessionPortalGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponsePortalUrlResponse2>;

    /**
     * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
     * @summary Get Session User
     * @param {SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSessionUserApiBetaSessionSessionIdUserGet(requestParameters: SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionUserResponse2>;

    /**
     * Initialize a new session with company API key.
     * @summary Init Session
     * @param {SessionApiInitSessionApiBetaSessionInitPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    initSessionApiBetaSessionInitPost(requestParameters: SessionApiInitSessionApiBetaSessionInitPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseTokenResponseData2>;

    /**
     * Start a session with a one-time token.
     * @summary Start Session
     * @param {SessionApiStartSessionApiBetaSessionStartPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startSessionApiBetaSessionStartPost(requestParameters: SessionApiStartSessionApiBetaSessionStartPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticBrokerFactoryCoreStandardModelsAbstractResponsesFinaticResponseSessionResponseData2>;

}

/**
 * Request parameters for getPortalUrlApiBetaSessionPortalGet operation in SessionApi.
 */
export interface SessionApiGetPortalUrlApiBetaSessionPortalGetRequest {
    /**
     * Session ID
     */
    readonly sessionId: string
}

/**
 * Request parameters for getSessionUserApiBetaSessionSessionIdUserGet operation in SessionApi.
 */
export interface SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest {
    /**
     * Session ID
     */
    readonly sessionId: string

    /**
     * Session ID from header (must match path parameter)
     */
    readonly xSessionId: string
}

/**
 * Request parameters for initSessionApiBetaSessionInitPost operation in SessionApi.
 */
export interface SessionApiInitSessionApiBetaSessionInitPostRequest {
    /**
     * Company API key
     */
    readonly xApiKey: string
}

/**
 * Request parameters for startSessionApiBetaSessionStartPost operation in SessionApi.
 */
export interface SessionApiStartSessionApiBetaSessionStartPostRequest {
    /**
     * One-time use token obtained from init_session endpoint to authenticate and start the session
     */
    readonly oneTimeToken: string

    /**
     * Session start request containing optional user ID to associate with the session
     */
    readonly sessionStartRequest: SessionStartRequest
}

/**
 * SessionApi - object-oriented interface
 */
export class SessionApi extends BaseAPI implements SessionApiInterface {
    /**
     * Get a portal URL with token for a session.  The session must be in ACTIVE or AUTHENTICATING state and the request must come from the same device that initiated the session. Device info is automatically validated from the request.
     * @summary Get Portal Url
     * @param {SessionApiGetPortalUrlApiBetaSessionPortalGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPortalUrlApiBetaSessionPortalGet(requestParameters: SessionApiGetPortalUrlApiBetaSessionPortalGetRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).getPortalUrlApiBetaSessionPortalGet(requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get user information for a completed session.  This endpoint is designed for server SDKs to retrieve user information after successful OTP verification.   Security: - Requires valid session in ACTIVE state - Validates device fingerprint binding - Only accessible to authenticated sessions with user_id - Validates that header session_id matches path session_id
     * @summary Get Session User
     * @param {SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSessionUserApiBetaSessionSessionIdUserGet(requestParameters: SessionApiGetSessionUserApiBetaSessionSessionIdUserGetRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).getSessionUserApiBetaSessionSessionIdUserGet(requestParameters.sessionId, requestParameters.xSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initialize a new session with company API key.
     * @summary Init Session
     * @param {SessionApiInitSessionApiBetaSessionInitPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public initSessionApiBetaSessionInitPost(requestParameters: SessionApiInitSessionApiBetaSessionInitPostRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).initSessionApiBetaSessionInitPost(requestParameters.xApiKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start a session with a one-time token.
     * @summary Start Session
     * @param {SessionApiStartSessionApiBetaSessionStartPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public startSessionApiBetaSessionStartPost(requestParameters: SessionApiStartSessionApiBetaSessionStartPostRequest, options?: RawAxiosRequestConfig) {
        return SessionApiFp(this.configuration).startSessionApiBetaSessionStartPost(requestParameters.oneTimeToken, requestParameters.sessionStartRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

