/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateSessionRequest } from '../models';
// @ts-ignore
import type { FinaticAPIErrorResponse } from '../models';
// @ts-ignore
import type { FinaticEnvironment } from '../models';
// @ts-ignore
import type { FinaticResponseDictStrUnionStrNoneType } from '../models';
// @ts-ignore
import type { FinaticResponseSessionResponseData } from '../models';
// @ts-ignore
import type { FinaticResponseSessionSyncStatusResponse } from '../models';
// @ts-ignore
import type { FinaticResponseTokenResponseData } from '../models';
/**
 * SessionsApi - axios parameter creator
 */
export const SessionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a v1 session by id.
         * @summary Get Session
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetSessionsSessionId: async (sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('finaticV1GetSessionsSessionId', 'sessionId', sessionId)
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('finaticV1GetSessionsSessionId', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/sessions/{sessionId}`
                .replace('{sessionId}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = typeof xFinaticEnvironment === 'string'
                    ? xFinaticEnvironment
                    : JSON.stringify(xFinaticEnvironment, replaceWithSerializableTypeIfNeeded);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Poll selected-account sync readiness for a v1 session.
         * @summary Get Session Sync Status
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetSessionsSessionIdSyncStatus: async (sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('finaticV1GetSessionsSessionIdSyncStatus', 'sessionId', sessionId)
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('finaticV1GetSessionsSessionIdSyncStatus', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/sessions/{sessionId}/sync-status`
                .replace('{sessionId}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = typeof xFinaticEnvironment === 'string'
                    ? xFinaticEnvironment
                    : JSON.stringify(xFinaticEnvironment, replaceWithSerializableTypeIfNeeded);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Compatibility user polling route for plural sessions.
         * @summary Get Session User
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetSessionsSessionIdUser: async (sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('finaticV1GetSessionsSessionIdUser', 'sessionId', sessionId)
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('finaticV1GetSessionsSessionIdUser', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/sessions/{sessionId}/user`
                .replace('{sessionId}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = typeof xFinaticEnvironment === 'string'
                    ? xFinaticEnvironment
                    : JSON.stringify(xFinaticEnvironment, replaceWithSerializableTypeIfNeeded);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create an account-first v1 session from a company API key.
         * @summary Create Session
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {CreateSessionRequest | null} [createSessionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostSessions: async (xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, createSessionRequest?: CreateSessionRequest | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('finaticV1PostSessions', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = typeof xFinaticEnvironment === 'string'
                    ? xFinaticEnvironment
                    : JSON.stringify(xFinaticEnvironment, replaceWithSerializableTypeIfNeeded);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSessionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a one-time portal link token for a v1 session.
         * @summary Create Portal Link
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostSessionsSessionIdPortalLinks: async (sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('finaticV1PostSessionsSessionIdPortalLinks', 'sessionId', sessionId)
            // verify required parameter 'xApiKey' is not null or undefined
            assertParamExists('finaticV1PostSessionsSessionIdPortalLinks', 'xApiKey', xApiKey)
            const localVarPath = `/api/v1/sessions/{sessionId}/portal-links`
                .replace('{sessionId}', encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = typeof xFinaticEnvironment === 'string'
                    ? xFinaticEnvironment
                    : JSON.stringify(xFinaticEnvironment, replaceWithSerializableTypeIfNeeded);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionsApi - functional programming interface
 */
export const SessionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a v1 session by id.
         * @summary Get Session
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1GetSessionsSessionId(sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseSessionResponseData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetSessionsSessionId(sessionId, xApiKey, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.finaticV1GetSessionsSessionId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Poll selected-account sync readiness for a v1 session.
         * @summary Get Session Sync Status
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1GetSessionsSessionIdSyncStatus(sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseSessionSyncStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetSessionsSessionIdSyncStatus(sessionId, xApiKey, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.finaticV1GetSessionsSessionIdSyncStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Compatibility user polling route for plural sessions.
         * @summary Get Session User
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1GetSessionsSessionIdUser(sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrUnionStrNoneType>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetSessionsSessionIdUser(sessionId, xApiKey, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.finaticV1GetSessionsSessionIdUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create an account-first v1 session from a company API key.
         * @summary Create Session
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {CreateSessionRequest | null} [createSessionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1PostSessions(xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, createSessionRequest?: CreateSessionRequest | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseSessionResponseData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1PostSessions(xApiKey, xFinaticEnvironment, createSessionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.finaticV1PostSessions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a one-time portal link token for a v1 session.
         * @summary Create Portal Link
         * @param {string} sessionId 
         * @param {string} xApiKey Company API key
         * @param {FinaticEnvironment} [xFinaticEnvironment] Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1PostSessionsSessionIdPortalLinks(sessionId: string, xApiKey: string, xFinaticEnvironment?: FinaticEnvironment, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseTokenResponseData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1PostSessionsSessionIdPortalLinks(sessionId, xApiKey, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.finaticV1PostSessionsSessionIdPortalLinks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SessionsApi - factory interface
 */
export const SessionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionsApiFp(configuration)
    return {
        /**
         * Get a v1 session by id.
         * @summary Get Session
         * @param {SessionsApiFinaticV1GetSessionsSessionIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetSessionsSessionId(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionResponseData> {
            return localVarFp.finaticV1GetSessionsSessionId(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Poll selected-account sync readiness for a v1 session.
         * @summary Get Session Sync Status
         * @param {SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetSessionsSessionIdSyncStatus(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionSyncStatusResponse> {
            return localVarFp.finaticV1GetSessionsSessionIdSyncStatus(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Compatibility user polling route for plural sessions.
         * @summary Get Session User
         * @param {SessionsApiFinaticV1GetSessionsSessionIdUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetSessionsSessionIdUser(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseDictStrUnionStrNoneType> {
            return localVarFp.finaticV1GetSessionsSessionIdUser(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Create an account-first v1 session from a company API key.
         * @summary Create Session
         * @param {SessionsApiFinaticV1PostSessionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostSessions(requestParameters: SessionsApiFinaticV1PostSessionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionResponseData> {
            return localVarFp.finaticV1PostSessions(requestParameters.xApiKey, requestParameters.xFinaticEnvironment, requestParameters.createSessionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a one-time portal link token for a v1 session.
         * @summary Create Portal Link
         * @param {SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostSessionsSessionIdPortalLinks(requestParameters: SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseTokenResponseData> {
            return localVarFp.finaticV1PostSessionsSessionIdPortalLinks(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SessionsApi - interface
 */
export interface SessionsApiInterface {
    /**
     * Get a v1 session by id.
     * @summary Get Session
     * @param {SessionsApiFinaticV1GetSessionsSessionIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetSessionsSessionId(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionResponseData>;

    /**
     * Poll selected-account sync readiness for a v1 session.
     * @summary Get Session Sync Status
     * @param {SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetSessionsSessionIdSyncStatus(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionSyncStatusResponse>;

    /**
     * Compatibility user polling route for plural sessions.
     * @summary Get Session User
     * @param {SessionsApiFinaticV1GetSessionsSessionIdUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetSessionsSessionIdUser(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseDictStrUnionStrNoneType>;

    /**
     * Create an account-first v1 session from a company API key.
     * @summary Create Session
     * @param {SessionsApiFinaticV1PostSessionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostSessions(requestParameters: SessionsApiFinaticV1PostSessionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseSessionResponseData>;

    /**
     * Create a one-time portal link token for a v1 session.
     * @summary Create Portal Link
     * @param {SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostSessionsSessionIdPortalLinks(requestParameters: SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseTokenResponseData>;

}

/**
 * Request parameters for finaticV1GetSessionsSessionId operation in SessionsApi.
 */
export interface SessionsApiFinaticV1GetSessionsSessionIdRequest {
    readonly sessionId: string

    /**
     * Company API key
     */
    readonly xApiKey: string

    /**
     * Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     */
    readonly xFinaticEnvironment?: FinaticEnvironment
}

/**
 * Request parameters for finaticV1GetSessionsSessionIdSyncStatus operation in SessionsApi.
 */
export interface SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest {
    readonly sessionId: string

    /**
     * Company API key
     */
    readonly xApiKey: string

    /**
     * Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     */
    readonly xFinaticEnvironment?: FinaticEnvironment
}

/**
 * Request parameters for finaticV1GetSessionsSessionIdUser operation in SessionsApi.
 */
export interface SessionsApiFinaticV1GetSessionsSessionIdUserRequest {
    readonly sessionId: string

    /**
     * Company API key
     */
    readonly xApiKey: string

    /**
     * Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     */
    readonly xFinaticEnvironment?: FinaticEnvironment
}

/**
 * Request parameters for finaticV1PostSessions operation in SessionsApi.
 */
export interface SessionsApiFinaticV1PostSessionsRequest {
    /**
     * Company API key
     */
    readonly xApiKey: string

    /**
     * Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     */
    readonly xFinaticEnvironment?: FinaticEnvironment

    readonly createSessionRequest?: CreateSessionRequest | null
}

/**
 * Request parameters for finaticV1PostSessionsSessionIdPortalLinks operation in SessionsApi.
 */
export interface SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest {
    readonly sessionId: string

    /**
     * Company API key
     */
    readonly xApiKey: string

    /**
     * Select the Finatic environment for account-first v1 calls. Defaults to the API-key environment when omitted.
     */
    readonly xFinaticEnvironment?: FinaticEnvironment
}

/**
 * SessionsApi - object-oriented interface
 */
export class SessionsApi extends BaseAPI implements SessionsApiInterface {
    /**
     * Get a v1 session by id.
     * @summary Get Session
     * @param {SessionsApiFinaticV1GetSessionsSessionIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1GetSessionsSessionId(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).finaticV1GetSessionsSessionId(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Poll selected-account sync readiness for a v1 session.
     * @summary Get Session Sync Status
     * @param {SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1GetSessionsSessionIdSyncStatus(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdSyncStatusRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).finaticV1GetSessionsSessionIdSyncStatus(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Compatibility user polling route for plural sessions.
     * @summary Get Session User
     * @param {SessionsApiFinaticV1GetSessionsSessionIdUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1GetSessionsSessionIdUser(requestParameters: SessionsApiFinaticV1GetSessionsSessionIdUserRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).finaticV1GetSessionsSessionIdUser(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create an account-first v1 session from a company API key.
     * @summary Create Session
     * @param {SessionsApiFinaticV1PostSessionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1PostSessions(requestParameters: SessionsApiFinaticV1PostSessionsRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).finaticV1PostSessions(requestParameters.xApiKey, requestParameters.xFinaticEnvironment, requestParameters.createSessionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a one-time portal link token for a v1 session.
     * @summary Create Portal Link
     * @param {SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1PostSessionsSessionIdPortalLinks(requestParameters: SessionsApiFinaticV1PostSessionsSessionIdPortalLinksRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).finaticV1PostSessionsSessionIdPortalLinks(requestParameters.sessionId, requestParameters.xApiKey, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }
}

