/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FDXWebhookSubscriptionCreate } from '../models';
// @ts-ignore
import type { FDXWebhookSubscriptionUpdate } from '../models';
// @ts-ignore
import type { FinaticAPIErrorResponse } from '../models';
// @ts-ignore
import type { FinaticResponseDictStrObject } from '../models';
// @ts-ignore
import type { FinaticResponseFDXWebhookSubscription } from '../models';
// @ts-ignore
import type { FinaticResponseListFDXWebhookEventDefinition } from '../models';
// @ts-ignore
import type { FinaticResponseListFDXWebhookSubscription } from '../models';
/**
 * WebhooksApi - axios parameter creator
 */
export const WebhooksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List supported outbound webhook event types.
         * @summary Get Webhook Catalog
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetWebhooksCatalog: async (xFinaticEnvironment?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/webhooks/catalog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return the documented outbound webhook payload JSON schema.
         * @summary Get Webhook Payload Schema
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetWebhooksPayloadSchema: async (xFinaticEnvironment?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/webhooks/payload-schema`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List webhook subscriptions for the current company account.
         * @summary List Webhook Subscriptions
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetWebhooksSubscriptions: async (xFinaticEnvironment?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/webhooks/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update a webhook subscription for the current company account.
         * @summary Update Webhook Subscription
         * @param {string} subscriptionId 
         * @param {FDXWebhookSubscriptionUpdate} fDXWebhookSubscriptionUpdate 
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PatchWebhooksSubscriptionsSubscriptionId: async (subscriptionId: string, fDXWebhookSubscriptionUpdate: FDXWebhookSubscriptionUpdate, xFinaticEnvironment?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('finaticV1PatchWebhooksSubscriptionsSubscriptionId', 'subscriptionId', subscriptionId)
            // verify required parameter 'fDXWebhookSubscriptionUpdate' is not null or undefined
            assertParamExists('finaticV1PatchWebhooksSubscriptionsSubscriptionId', 'fDXWebhookSubscriptionUpdate', fDXWebhookSubscriptionUpdate)
            const localVarPath = `/api/v1/webhooks/subscriptions/{subscriptionId}`
                .replace('{subscriptionId}', encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fDXWebhookSubscriptionUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a webhook subscription for the current company account.
         * @summary Create Webhook Subscription
         * @param {FDXWebhookSubscriptionCreate} fDXWebhookSubscriptionCreate 
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostWebhooksSubscriptions: async (fDXWebhookSubscriptionCreate: FDXWebhookSubscriptionCreate, xFinaticEnvironment?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fDXWebhookSubscriptionCreate' is not null or undefined
            assertParamExists('finaticV1PostWebhooksSubscriptions', 'fDXWebhookSubscriptionCreate', fDXWebhookSubscriptionCreate)
            const localVarPath = `/api/v1/webhooks/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fDXWebhookSubscriptionCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke a webhook subscription for the current company account.
         * @summary Revoke Webhook Subscription
         * @param {string} subscriptionId 
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke: async (subscriptionId: string, xFinaticEnvironment?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/webhooks/subscriptions/{subscriptionId}/revoke`
                .replace('{subscriptionId}', encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xFinaticEnvironment != null) {
                localVarHeaderParameter['X-Finatic-Environment'] = String(xFinaticEnvironment);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebhooksApi - functional programming interface
 */
export const WebhooksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebhooksApiAxiosParamCreator(configuration)
    return {
        /**
         * List supported outbound webhook event types.
         * @summary Get Webhook Catalog
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1GetWebhooksCatalog(xFinaticEnvironment?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListFDXWebhookEventDefinition>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetWebhooksCatalog(xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.finaticV1GetWebhooksCatalog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return the documented outbound webhook payload JSON schema.
         * @summary Get Webhook Payload Schema
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1GetWebhooksPayloadSchema(xFinaticEnvironment?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseDictStrObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetWebhooksPayloadSchema(xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.finaticV1GetWebhooksPayloadSchema']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List webhook subscriptions for the current company account.
         * @summary List Webhook Subscriptions
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1GetWebhooksSubscriptions(xFinaticEnvironment?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseListFDXWebhookSubscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1GetWebhooksSubscriptions(xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.finaticV1GetWebhooksSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update a webhook subscription for the current company account.
         * @summary Update Webhook Subscription
         * @param {string} subscriptionId 
         * @param {FDXWebhookSubscriptionUpdate} fDXWebhookSubscriptionUpdate 
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1PatchWebhooksSubscriptionsSubscriptionId(subscriptionId: string, fDXWebhookSubscriptionUpdate: FDXWebhookSubscriptionUpdate, xFinaticEnvironment?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseFDXWebhookSubscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1PatchWebhooksSubscriptionsSubscriptionId(subscriptionId, fDXWebhookSubscriptionUpdate, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.finaticV1PatchWebhooksSubscriptionsSubscriptionId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a webhook subscription for the current company account.
         * @summary Create Webhook Subscription
         * @param {FDXWebhookSubscriptionCreate} fDXWebhookSubscriptionCreate 
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1PostWebhooksSubscriptions(fDXWebhookSubscriptionCreate: FDXWebhookSubscriptionCreate, xFinaticEnvironment?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseFDXWebhookSubscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1PostWebhooksSubscriptions(fDXWebhookSubscriptionCreate, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.finaticV1PostWebhooksSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Revoke a webhook subscription for the current company account.
         * @summary Revoke Webhook Subscription
         * @param {string} subscriptionId 
         * @param {string | null} [xFinaticEnvironment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(subscriptionId: string, xFinaticEnvironment?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinaticResponseFDXWebhookSubscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(subscriptionId, xFinaticEnvironment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebhooksApi.finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WebhooksApi - factory interface
 */
export const WebhooksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebhooksApiFp(configuration)
    return {
        /**
         * List supported outbound webhook event types.
         * @summary Get Webhook Catalog
         * @param {WebhooksApiFinaticV1GetWebhooksCatalogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetWebhooksCatalog(requestParameters: WebhooksApiFinaticV1GetWebhooksCatalogRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseListFDXWebhookEventDefinition> {
            return localVarFp.finaticV1GetWebhooksCatalog(requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Return the documented outbound webhook payload JSON schema.
         * @summary Get Webhook Payload Schema
         * @param {WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetWebhooksPayloadSchema(requestParameters: WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseDictStrObject> {
            return localVarFp.finaticV1GetWebhooksPayloadSchema(requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * List webhook subscriptions for the current company account.
         * @summary List Webhook Subscriptions
         * @param {WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1GetWebhooksSubscriptions(requestParameters: WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseListFDXWebhookSubscription> {
            return localVarFp.finaticV1GetWebhooksSubscriptions(requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Update a webhook subscription for the current company account.
         * @summary Update Webhook Subscription
         * @param {WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PatchWebhooksSubscriptionsSubscriptionId(requestParameters: WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseFDXWebhookSubscription> {
            return localVarFp.finaticV1PatchWebhooksSubscriptionsSubscriptionId(requestParameters.subscriptionId, requestParameters.fDXWebhookSubscriptionUpdate, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a webhook subscription for the current company account.
         * @summary Create Webhook Subscription
         * @param {WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostWebhooksSubscriptions(requestParameters: WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseFDXWebhookSubscription> {
            return localVarFp.finaticV1PostWebhooksSubscriptions(requestParameters.fDXWebhookSubscriptionCreate, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke a webhook subscription for the current company account.
         * @summary Revoke Webhook Subscription
         * @param {WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(requestParameters: WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseFDXWebhookSubscription> {
            return localVarFp.finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(requestParameters.subscriptionId, requestParameters.xFinaticEnvironment, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebhooksApi - interface
 */
export interface WebhooksApiInterface {
    /**
     * List supported outbound webhook event types.
     * @summary Get Webhook Catalog
     * @param {WebhooksApiFinaticV1GetWebhooksCatalogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetWebhooksCatalog(requestParameters?: WebhooksApiFinaticV1GetWebhooksCatalogRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseListFDXWebhookEventDefinition>;

    /**
     * Return the documented outbound webhook payload JSON schema.
     * @summary Get Webhook Payload Schema
     * @param {WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetWebhooksPayloadSchema(requestParameters?: WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseDictStrObject>;

    /**
     * List webhook subscriptions for the current company account.
     * @summary List Webhook Subscriptions
     * @param {WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1GetWebhooksSubscriptions(requestParameters?: WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseListFDXWebhookSubscription>;

    /**
     * Update a webhook subscription for the current company account.
     * @summary Update Webhook Subscription
     * @param {WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PatchWebhooksSubscriptionsSubscriptionId(requestParameters: WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseFDXWebhookSubscription>;

    /**
     * Create a webhook subscription for the current company account.
     * @summary Create Webhook Subscription
     * @param {WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostWebhooksSubscriptions(requestParameters: WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseFDXWebhookSubscription>;

    /**
     * Revoke a webhook subscription for the current company account.
     * @summary Revoke Webhook Subscription
     * @param {WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(requestParameters: WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest, options?: RawAxiosRequestConfig): AxiosPromise<FinaticResponseFDXWebhookSubscription>;

}

/**
 * Request parameters for finaticV1GetWebhooksCatalog operation in WebhooksApi.
 */
export interface WebhooksApiFinaticV1GetWebhooksCatalogRequest {
    readonly xFinaticEnvironment?: string | null
}

/**
 * Request parameters for finaticV1GetWebhooksPayloadSchema operation in WebhooksApi.
 */
export interface WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest {
    readonly xFinaticEnvironment?: string | null
}

/**
 * Request parameters for finaticV1GetWebhooksSubscriptions operation in WebhooksApi.
 */
export interface WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest {
    readonly xFinaticEnvironment?: string | null
}

/**
 * Request parameters for finaticV1PatchWebhooksSubscriptionsSubscriptionId operation in WebhooksApi.
 */
export interface WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest {
    readonly subscriptionId: string

    readonly fDXWebhookSubscriptionUpdate: FDXWebhookSubscriptionUpdate

    readonly xFinaticEnvironment?: string | null
}

/**
 * Request parameters for finaticV1PostWebhooksSubscriptions operation in WebhooksApi.
 */
export interface WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest {
    readonly fDXWebhookSubscriptionCreate: FDXWebhookSubscriptionCreate

    readonly xFinaticEnvironment?: string | null
}

/**
 * Request parameters for finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke operation in WebhooksApi.
 */
export interface WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest {
    readonly subscriptionId: string

    readonly xFinaticEnvironment?: string | null
}

/**
 * WebhooksApi - object-oriented interface
 */
export class WebhooksApi extends BaseAPI implements WebhooksApiInterface {
    /**
     * List supported outbound webhook event types.
     * @summary Get Webhook Catalog
     * @param {WebhooksApiFinaticV1GetWebhooksCatalogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1GetWebhooksCatalog(requestParameters: WebhooksApiFinaticV1GetWebhooksCatalogRequest = {}, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).finaticV1GetWebhooksCatalog(requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return the documented outbound webhook payload JSON schema.
     * @summary Get Webhook Payload Schema
     * @param {WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1GetWebhooksPayloadSchema(requestParameters: WebhooksApiFinaticV1GetWebhooksPayloadSchemaRequest = {}, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).finaticV1GetWebhooksPayloadSchema(requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List webhook subscriptions for the current company account.
     * @summary List Webhook Subscriptions
     * @param {WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1GetWebhooksSubscriptions(requestParameters: WebhooksApiFinaticV1GetWebhooksSubscriptionsRequest = {}, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).finaticV1GetWebhooksSubscriptions(requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update a webhook subscription for the current company account.
     * @summary Update Webhook Subscription
     * @param {WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1PatchWebhooksSubscriptionsSubscriptionId(requestParameters: WebhooksApiFinaticV1PatchWebhooksSubscriptionsSubscriptionIdRequest, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).finaticV1PatchWebhooksSubscriptionsSubscriptionId(requestParameters.subscriptionId, requestParameters.fDXWebhookSubscriptionUpdate, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a webhook subscription for the current company account.
     * @summary Create Webhook Subscription
     * @param {WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1PostWebhooksSubscriptions(requestParameters: WebhooksApiFinaticV1PostWebhooksSubscriptionsRequest, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).finaticV1PostWebhooksSubscriptions(requestParameters.fDXWebhookSubscriptionCreate, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Revoke a webhook subscription for the current company account.
     * @summary Revoke Webhook Subscription
     * @param {WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(requestParameters: WebhooksApiFinaticV1PostWebhooksSubscriptionsSubscriptionIdRevokeRequest, options?: RawAxiosRequestConfig) {
        return WebhooksApiFp(this.configuration).finaticV1PostWebhooksSubscriptionsSubscriptionIdRevoke(requestParameters.subscriptionId, requestParameters.xFinaticEnvironment, options).then((request) => request(this.axios, this.basePath));
    }
}

