/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountOrderPayload } from './account-order-payload';

/**
 * Account-scoped order command body for place and modify.
 */
export interface AccountOrderCommandRequest {
  /**
   * Optional broker id hint for schema discrimination; must match the account grant when provided.
   */
  broker?: string | null;
  /**
   * Broker-specific order payload. Provider-specific fields are accepted and preserved.
   */
  order: AccountOrderPayload;
  /**
   * Explicit per-operation confirmation for paper-trading writes. Public sandbox orders are rejected unless this is true.
   */
  paperTradeConfirmed?: boolean;
}
