/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Accounts {
  id?: string | null;
  api_key_created_at?: string | null;
  api_key_expires_at?: string | null;
  api_key_hash?: string | null;
  api_key_last_used_at?: string | null;
  compliance_agreement?: boolean | null;
  created_at: string | null;
  created_by?: string | null;
  email?: string | null;
  is_personal_account: boolean;
  name: string;
  onboarding_completed?: boolean | null;
  onboarding_step?: number | null;
  picture_url?: string | null;
  primary_owner_user_id: string;
  public_data: any;
  referral_source?: string | null;
  sandbox_api_key_hash?: string | null;
  sandbox_key_created_at?: string | null;
  sandbox_key_expires_at?: string | null;
  sandbox_key_last_used_at?: string | null;
  slug?: string | null;
  terms_accepted_at?: string | null;
  trading_enabled?: boolean | null;
  trading_usage_description?: string | null;
  updated_at: string | null;
  updated_by?: string | null;
  use_case_features?: null;
}
