/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Notional1 } from './notional1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';
// May contain unused imports in some cases
// @ts-ignore
import type { TrailPercent } from './trail-percent';
// May contain unused imports in some cases
// @ts-ignore
import type { TrailPrice } from './trail-price';

/**
 * Equity market order.
 */
export interface AlpacaEquityMarketOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': AlpacaEquityMarketOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: AlpacaEquityMarketOrderPlaceQueryParamsAssetTypeEnum;
    'action': AlpacaEquityMarketOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce1;
    'symbol': string;
    'orderQty': number;
    'client_order_id'?: string | null;
    'extended_hours'?: boolean | null;
    'order_class'?: string | null;
    'notional'?: Notional1 | null;
    'take_profit'?: { [key: string]: any; } | null;
    'stop_loss'?: { [key: string]: any; } | null;
    'trail_percent'?: TrailPercent | null;
    'trail_price'?: TrailPrice | null;
    'legs'?: Array<{ [key: string]: any; }> | null;
}

export enum AlpacaEquityMarketOrderPlaceQueryParamsOrderTypeEnum {
    Market = 'market'
}
export enum AlpacaEquityMarketOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum AlpacaEquityMarketOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


