/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Notional1 } from './notional1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Crypto market order.
 */
export interface AlpacaCryptoMarketOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': AlpacaCryptoMarketOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: AlpacaCryptoMarketOrderPlaceQueryParamsAssetTypeEnum;
    'action': AlpacaCryptoMarketOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': number;
    'client_order_id'?: string | null;
    'order_class'?: string | null;
    'notional'?: Notional1 | null;
}

export enum AlpacaCryptoMarketOrderPlaceQueryParamsOrderTypeEnum {
    Market = 'market'
}
export enum AlpacaCryptoMarketOrderPlaceQueryParamsAssetTypeEnum {
    Crypto = 'crypto'
}
export enum AlpacaCryptoMarketOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


