/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Notional1 } from './notional1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Option limit order.
 */
export interface AlpacaOptionLimitOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': AlpacaOptionLimitOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: AlpacaOptionLimitOrderPlaceQueryParamsAssetTypeEnum;
    'action': AlpacaOptionLimitOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': number;
    'price': number;
    'client_order_id'?: string | null;
    'extended_hours'?: boolean | null;
    'order_class'?: string | null;
    'notional'?: Notional1 | null;
    'take_profit'?: { [key: string]: any; } | null;
    'stop_loss'?: { [key: string]: any; } | null;
    'legs'?: Array<{ [key: string]: any; }> | null;
}

export enum AlpacaOptionLimitOrderPlaceQueryParamsOrderTypeEnum {
    Limit = 'limit'
}
export enum AlpacaOptionLimitOrderPlaceQueryParamsAssetTypeEnum {
    EquityOption = 'equity_option'
}
export enum AlpacaOptionLimitOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


