/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Notional2 } from './notional2';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Crypto stop limit order.
 */
export interface AlpacaCryptoStopLimitOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': AlpacaCryptoStopLimitOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: AlpacaCryptoStopLimitOrderPlaceQueryParamsAssetTypeEnum;
    'action': AlpacaCryptoStopLimitOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce1;
    'symbol': string;
    'orderQty': number;
    'stopPrice': number;
    'limitPrice': number;
    'client_order_id'?: string | null;
    'order_class'?: string | null;
    'notional'?: Notional2 | null;
}

export enum AlpacaCryptoStopLimitOrderPlaceQueryParamsOrderTypeEnum {
    StopLimit = 'stop_limit'
}
export enum AlpacaCryptoStopLimitOrderPlaceQueryParamsAssetTypeEnum {
    Crypto = 'crypto'
}
export enum AlpacaCryptoStopLimitOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


