/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber } from './accountnumber';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaOrderCancelQueryParams } from './alpaca-order-cancel-query-params';

/**
 * Alpaca cancel-order request body.  Attributes ---------- broker : Literal[\"alpaca\"]     Discriminator; must be ``\"alpaca\"``. account_number : str | int     Broker-provided account number (top-level). Serialized as ``accountNumber``. order : AlpacaOrderCancelQueryParams     Alpaca-specific cancel parameters (e.g. order_id).  Notes ----- Uses ``extra=\"forbid\"`` and ``populate_by_name=True``.
 */
export interface AlpacaOrderCancelRequest {
  broker: AlpacaOrderCancelRequestBrokerEnum;
  accountNumber: Accountnumber;
  order: AlpacaOrderCancelQueryParams;
}

export enum AlpacaOrderCancelRequestBrokerEnum {
  Alpaca = 'alpaca',
}
