/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model for broker information.
 */
export interface BrokerInfo {
    'id': string;
    'name': string;
    'display_name': string;
    'description': string;
    'website': string;
    'features': Array<string>;
    'auth_type': BrokerInfoAuthTypeEnum;
    'logo_path': string;
    'is_active': boolean;
    'kind'?: string;
    'company_metadata'?: { [key: string]: any; };
    'supports_trading'?: boolean;
    'api_passphrase_required'?: boolean;
    'api_passphrase_optional'?: boolean;
    'is_beta'?: boolean;
    'is_alpha'?: boolean;
    'is_disabled'?: boolean;
    'is_alias'?: boolean;
    'base_broker_id'?: string | null;
}

export enum BrokerInfoAuthTypeEnum {
    Oauth = 'oauth',
    UsernamePassword = 'username_password',
    ApiKey = 'api_key',
    PushAgent = 'push_agent'
}


