/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber } from './accountnumber';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaOrderCancelRequest } from './alpaca-order-cancel-request';
// May contain unused imports in some cases
// @ts-ignore
import type { NinjaTraderOrderCancelRequest } from './ninja-trader-order-cancel-request';
// May contain unused imports in some cases
// @ts-ignore
import type { RobinhoodOrderCancelRequest } from './robinhood-order-cancel-request';
// May contain unused imports in some cases
// @ts-ignore
import type { TastyTradeOrderCancelRequest } from './tasty-trade-order-cancel-request';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationOrderCancelRequest } from './tradestation-order-cancel-request';
// May contain unused imports in some cases
// @ts-ignore
import type { Trading212OrderCancelRequest } from './trading212-order-cancel-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullOrderCancelQueryParams } from './webull-order-cancel-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullOrderCancelRequest } from './webull-order-cancel-request';

/**
 * @type CancelOrderApiBetaBrokersOrdersOrderIdDeleteRequest
 * Broker-specific parameters object for *cancel order* operations
 */
export type CancelOrderApiBetaBrokersOrdersOrderIdDeleteRequest =
  | ({ broker: 'alpaca' } & AlpacaOrderCancelRequest)
  | ({ broker: 'ninja_trader' } & NinjaTraderOrderCancelRequest)
  | ({ broker: 'robinhood' } & RobinhoodOrderCancelRequest)
  | ({ broker: 'tasty_trade' } & TastyTradeOrderCancelRequest)
  | ({ broker: 'tradestation' } & TradestationOrderCancelRequest)
  | ({ broker: 'trading212' } & Trading212OrderCancelRequest)
  | ({ broker: 'webull' } & WebullOrderCancelRequest);
