/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber1 } from './accountnumber1';
// May contain unused imports in some cases
// @ts-ignore
import type { EtoroOrderPlaceQueryParams } from './etoro-order-place-query-params';

/**
 * eToro place-order request body (market by amount/units). OAuth.
 */
export interface EtoroOrderPlaceRequest {
    'broker': EtoroOrderPlaceRequestBrokerEnum;
    'accountNumber': Accountnumber1;
    'order': EtoroOrderPlaceQueryParams;
}

export enum EtoroOrderPlaceRequestBrokerEnum {
    Etoro = 'etoro'
}


