/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * eToro market order: by amount (cash) or by units.  Use instrument_id from market-data search. One of amount or units required.
 */
export interface EtoroOrderPlaceQueryParams {
  [key: string]: any;

  /**
   * eToro instrument ID (from search)
   */
  instrument_id: number;
  /**
   * Cash amount (by-amount endpoint)
   */
  amount?: number | null;
  /**
   * Number of units (by-units endpoint)
   */
  units?: number | null;
  /**
   * Buy or sell
   */
  action: EtoroOrderPlaceQueryParamsActionEnum;
  /**
   * Use demo execution environment
   */
  is_demo?: boolean;
  /**
   * Leverage
   */
  leverage?: number;
  /**
   * Optional stop loss
   */
  stop_loss?: number | null;
  /**
   * Optional take profit
   */
  take_profit?: number | null;
}

export enum EtoroOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
