/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Eventtype } from './eventtype';
// May contain unused imports in some cases
// @ts-ignore
import type { FDXInstrumentDescriptor } from './fdxinstrument-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { Orderstatus } from './orderstatus';
// May contain unused imports in some cases
// @ts-ignore
import type { Previousstatus } from './previousstatus';

/**
 * FDX-style order event schema for lifecycle tracking.  Represents order lifecycle events and state changes.
 */
export interface FDXBrokerOrderEvent {
  _id?: string;
  /**
   * Ordered instrument identities aligned to affectedLegs
   */
  affectedInstruments?: Array<FDXInstrumentDescriptor> | null;
  /**
   * Leg indices affected by this event
   */
  affectedLegs?: Array<number> | null;
  /**
   * Confidence score (0-1) for inferred events
   */
  confidence?: number | null;
  /**
   * Event category (status change, structural, etc.)
   */
  eventCategory?: string | null;
  /**
   * Event identifier (for idempotency)
   */
  eventId: string;
  /**
   * Broker-reported event time
   */
  eventTime: string;
  eventType: Eventtype;
  /**
   * Whether relationship was inferred
   */
  inferred?: boolean | null;
  /**
   * Extended broker-specific data (excluded when None for FDX compliance)
   */
  metadata?: { [key: string]: any } | null;
  /**
   * Associated group (if applicable)
   */
  orderGroupId?: string | null;
  /**
   * Associated order identifier
   */
  orderId: string;
  orderStatus?: Orderstatus | null;
  previousStatus?: Previousstatus | null;
  /**
   * Reason for event or inference
   */
  reasonCode?: string | null;
  /**
   * Server recording time (optional, falls back to eventTime if not available)
   */
  recordedAt?: string | null;
  /**
   * Related event (for event chains)
   */
  relatedEventId?: string | null;
  /**
   * Related order (for REPLACED_BY, OCO_LINK, etc.)
   */
  relatedOrderId?: string | null;
}
