/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Commissionshare } from './commissionshare';
// May contain unused imports in some cases
// @ts-ignore
import type { Fillprice } from './fillprice';
// May contain unused imports in some cases
// @ts-ignore
import type { Fillquantity } from './fillquantity';

/**
 * FDX-style position lot fill schema.  Represents individual fills associated with position lots for tax lot tracking.
 */
export interface FDXBrokerPositionLotFill {
    '_id'?: string;
    /**
     * Lot fill identifier
     */
    'lotFillId': string;
    /**
     * Associated position lot identifier
     */
    'lotId': string;
    /**
     * Associated order fill identifier
     */
    'orderFillId': string;
    'fillQuantity': Fillquantity;
    'fillPrice': Fillprice;
    'commissionShare'?: Commissionshare | null;
    /**
     * Execution timestamp
     */
    'executedAt': string;
    'metadata'?: { [key: string]: any; } | null;
}

