/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Assettype } from './assettype';
// May contain unused imports in some cases
// @ts-ignore
import type { Commission1 } from './commission1';
// May contain unused imports in some cases
// @ts-ignore
import type { FDXInstrumentDescriptor } from './fdxinstrument-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { Price } from './price';
// May contain unused imports in some cases
// @ts-ignore
import type { Quantity1 } from './quantity1';
// May contain unused imports in some cases
// @ts-ignore
import type { Securityidtype } from './securityidtype';
// May contain unused imports in some cases
// @ts-ignore
import type { Side1 } from './side1';

/**
 * FDX-style order fill/execution schema.  Represents individual order executions/fills.
 */
export interface FDXBrokerOrderFill {
  _id?: string;
  assetType: Assettype;
  commission?: Commission1 | null;
  /**
   * Broker execution timestamp
   */
  executedAt: string;
  /**
   * Broker execution ID
   */
  executionId?: string | null;
  /**
   * Finatic fill ID
   */
  fillId: string;
  /**
   * Versioned Finatic instrument identity
   */
  instrument?: FDXInstrumentDescriptor | null;
  /**
   * Associated leg (for multi-leg orders)
   */
  legId?: string | null;
  /**
   * Extended broker-specific data (excluded when None for FDX compliance)
   */
  metadata?: { [key: string]: any } | null;
  /**
   * Parent order identifier
   */
  orderId: string;
  price: Price;
  quantity: Quantity1;
  /**
   * Security identifier
   */
  securityId: string;
  securityIdType: Securityidtype;
  side: Side1;
  /**
   * Broker trade ID
   */
  tradeId?: string | null;
  /**
   * Execution venue/exchange
   */
  venue?: string | null;
}
