/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Assettype } from './assettype';
// May contain unused imports in some cases
// @ts-ignore
import type { Averagebuyprice } from './averagebuyprice';
// May contain unused imports in some cases
// @ts-ignore
import type { Averagesellprice } from './averagesellprice';
// May contain unused imports in some cases
// @ts-ignore
import type { Costbasis } from './costbasis';
// May contain unused imports in some cases
// @ts-ignore
import type { Costbasiswithcommission } from './costbasiswithcommission';
// May contain unused imports in some cases
// @ts-ignore
import type { Currentprice } from './currentprice';
// May contain unused imports in some cases
// @ts-ignore
import type { FDXInstrumentDescriptor } from './fdxinstrument-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { Marketvalue } from './marketvalue';
// May contain unused imports in some cases
// @ts-ignore
import type { Quantity2 } from './quantity2';
// May contain unused imports in some cases
// @ts-ignore
import type { Realizedprofitloss } from './realizedprofitloss';
// May contain unused imports in some cases
// @ts-ignore
import type { Realizedprofitlosspercent } from './realizedprofitlosspercent';
// May contain unused imports in some cases
// @ts-ignore
import type { Realizedprofitlosswithcommission } from './realizedprofitlosswithcommission';
// May contain unused imports in some cases
// @ts-ignore
import type { Securityidtype } from './securityidtype';
// May contain unused imports in some cases
// @ts-ignore
import type { Side2 } from './side2';
// May contain unused imports in some cases
// @ts-ignore
import type { Status1 } from './status1';
// May contain unused imports in some cases
// @ts-ignore
import type { Units } from './units';
// May contain unused imports in some cases
// @ts-ignore
import type { Unrealizedprofitloss } from './unrealizedprofitloss';
// May contain unused imports in some cases
// @ts-ignore
import type { Unrealizedprofitlosspercent } from './unrealizedprofitlosspercent';

/**
 * FDX-style broker position schema.  Based on FDX Holdings, significantly extended for trading: - Short positions - Realized/unrealized P&L - Position lifecycle - Commission tracking
 */
export interface FDXBrokerPosition {
  /**
   * Broker account identifier
   */
  accountId: string;
  assetType: Assettype;
  averageBuyPrice?: Averagebuyprice | null;
  averageSellPrice?: Averagesellprice | null;
  /**
   * User-broker connection identifier
   */
  connectionId: string;
  costBasis?: Costbasis | null;
  costBasisWithCommission?: Costbasiswithcommission | null;
  currentPrice?: Currentprice | null;
  /**
   * Position UUID in Finatic database
   */
  id?: string;
  /**
   * Versioned Finatic instrument identity
   */
  instrument?: FDXInstrumentDescriptor | null;
  /**
   * Normalized instrument key
   */
  instrumentKey?: string | null;
  /**
   * Internal account UUID (Finatic account id)
   */
  internalAccountId?: string | null;
  marketValue?: Marketvalue | null;
  /**
   * Extended broker-specific data (excluded when None for FDX compliance)
   */
  metadata?: { [key: string]: any } | null;
  /**
   * Position close time
   */
  positionClosedAt?: string | null;
  /**
   * Position open time
   */
  positionCreatedAt?: string | null;
  /**
   * Position group identifier
   */
  positionGroupId?: string | null;
  /**
   * Last position update
   */
  positionUpdatedAt?: string | null;
  quantity: Quantity2;
  realizedProfitLoss?: Realizedprofitloss | null;
  realizedProfitLossPercent?: Realizedprofitlosspercent | null;
  realizedProfitLossWithCommission?: Realizedprofitlosswithcommission | null;
  /**
   * Symbol or instrument
   */
  securityId: string;
  securityIdType: Securityidtype;
  side?: Side2 | null;
  /**
   * Snapshot date
   */
  snapshotDate?: string | null;
  status?: Status1 | null;
  units?: Units | null;
  unrealizedProfitLoss?: Unrealizedprofitloss | null;
  unrealizedProfitLossPercent?: Unrealizedprofitlosspercent | null;
}
