/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FDXOrderGroupOrder } from './fdxorder-group-order';
// May contain unused imports in some cases
// @ts-ignore
import type { Grouptype } from './grouptype';

/**
 * FDX-style order group schema for multi-order workflows.  Represents groups of related orders (OCO, OTO, Bracket, etc.).
 */
export interface FDXBrokerOrderGroup {
  _id?: string;
  /**
   * Group identifier
   */
  orderGroupId: string;
  /**
   * User-broker connection identifier
   */
  connectionId: string;
  groupType?: Grouptype | null;
  groupStatus?: string | null;
  /**
   * Orders in this group
   */
  orders?: Array<FDXOrderGroupOrder>;
  createdAt?: string | null;
  updatedAt?: string | null;
  completedAt?: string | null;
  metadata?: { [key: string]: any } | null;
}
