/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Public FDX consent resource.
 */
export interface FDXConsentGrant {
  companyAccountId: string;
  consentedAt?: string | null;
  createdAt?: string | null;
  dataClusters?: Array<string>;
  durationDays?: number | null;
  expiresAt?: string | null;
  id: string;
  initiator: string;
  lookbackDays?: number | null;
  parties?: { [key: string]: any };
  resources?: Array<{ [key: string]: any }>;
  revocationReason?: string | null;
  revokedAt?: string | null;
  revokedBy?: string | null;
  status: string;
  updatedAt?: string | null;
  userId: string;
}
