/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Source-backed futures identity details.
 */
export interface FDXFutureInstrumentDetails {
  contractCode?: string | null;
  contractMonth?: string | null;
  exchangeMic?: string | null;
  expirationDate?: string | null;
  identityQuality: FDXFutureInstrumentDetailsIdentityQualityEnum;
  productRoot?: string | null;
}

export enum FDXFutureInstrumentDetailsIdentityQualityEnum {
  Exact = 'EXACT',
  RootOnly = 'ROOT_ONLY',
}
