/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FDXFutureInstrumentDetails } from './fdxfuture-instrument-details';

/**
 * Stable, non-secret Finatic identity attached to an FDX resource.
 */
export interface FDXInstrumentDescriptor {
  assetType: string;
  displaySymbol: string;
  finaticInstrumentId: string;
  future?: FDXFutureInstrumentDetails | null;
  observedAt?: string | null;
  provenance?: { [key: string]: string } | null;
  providerNativeId?: string | null;
  providerSymbol?: string | null;
  version?: FDXInstrumentDescriptorVersionEnum;
}

export enum FDXInstrumentDescriptorVersionEnum {
  _10 = '1.0',
}
