/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Assettype } from './assettype';
// May contain unused imports in some cases
// @ts-ignore
import type { Averagefillprice } from './averagefillprice';
// May contain unused imports in some cases
// @ts-ignore
import type { FDXInstrumentDescriptor } from './fdxinstrument-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { Filledquantity } from './filledquantity';
// May contain unused imports in some cases
// @ts-ignore
import type { Futureunderlyingassettype } from './futureunderlyingassettype';
// May contain unused imports in some cases
// @ts-ignore
import type { Limitprice } from './limitprice';
// May contain unused imports in some cases
// @ts-ignore
import type { Notional } from './notional';
// May contain unused imports in some cases
// @ts-ignore
import type { Positionintent } from './positionintent';
// May contain unused imports in some cases
// @ts-ignore
import type { Quantity } from './quantity';
// May contain unused imports in some cases
// @ts-ignore
import type { Remainingquantity } from './remainingquantity';
// May contain unused imports in some cases
// @ts-ignore
import type { Securityidtype } from './securityidtype';
// May contain unused imports in some cases
// @ts-ignore
import type { Side } from './side';
// May contain unused imports in some cases
// @ts-ignore
import type { Stopprice } from './stopprice';
// May contain unused imports in some cases
// @ts-ignore
import type { Strikeprice } from './strikeprice';

/**
 * FDX-style order leg schema for multi-leg orders.
 */
export interface FDXOrderLeg {
  assetType: Assettype;
  averageFillPrice?: Averagefillprice | null;
  /**
   * Raw symbol/contract from broker
   */
  brokerProvidedSymbol?: string | null;
  /**
   * Future contract code (e.g., ESZ4)
   */
  contractCode?: string | null;
  /**
   * Crypto base symbol
   */
  cryptoBaseSymbol?: string | null;
  /**
   * Crypto quote symbol
   */
  cryptoQuoteSymbol?: string | null;
  /**
   * Expiration date
   */
  expirationDate?: string | null;
  filledQuantity?: Filledquantity | null;
  futureUnderlyingAssetType?: Futureunderlyingassettype | null;
  /**
   * Versioned Finatic instrument identity
   */
  instrument?: FDXInstrumentDescriptor | null;
  /**
   * Leg index (0 for single-leg)
   */
  legIndex: number;
  limitPrice?: Limitprice | null;
  notional?: Notional | null;
  /**
   * Option type (CALL, PUT)
   */
  optionType?: string | null;
  positionIntent?: Positionintent | null;
  quantity: Quantity;
  remainingQuantity?: Remainingquantity | null;
  /**
   * Symbol or instrument identifier
   */
  securityId: string;
  securityIdType: Securityidtype;
  side: Side;
  stopPrice?: Stopprice | null;
  strikePrice?: Strikeprice | null;
  /**
   * Underlying symbol
   */
  underlyingSymbol?: string | null;
}
