/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Mutable webhook subscription fields.
 */
export interface FDXWebhookSubscriptionUpdate {
  _id?: string;
  description?: string | null;
  eventTypes?: Array<FDXWebhookSubscriptionUpdateEventTypesEnum> | null;
  status?: FDXWebhookSubscriptionUpdateStatusEnum | null;
  url?: string | null;
}

export enum FDXWebhookSubscriptionUpdateEventTypesEnum {
  AccountGrantCreated = 'account.grant.created',
  AccountGrantUpdated = 'account.grant.updated',
  AccountGrantRevoked = 'account.grant.revoked',
  AccountSyncStarted = 'account.sync.started',
  AccountSyncSucceeded = 'account.sync.succeeded',
  AccountSyncFailed = 'account.sync.failed',
  AccountBalanceUpdated = 'account.balance.updated',
  AccountPositionUpdated = 'account.position.updated',
  AccountTransactionCreated = 'account.transaction.created',
  OrderCreated = 'order.created',
  OrderUpdated = 'order.updated',
  OrderFilled = 'order.filled',
  OrderCancelled = 'order.cancelled',
  OrderRejected = 'order.rejected',
  ConnectionReauthRequired = 'connection.reauth.required',
}
export enum FDXWebhookSubscriptionUpdateStatusEnum {
  Active = 'active',
  Disabled = 'disabled',
  Revoked = 'revoked',
}
