/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SuccessPayloadTokenResponseData } from './success-payload-token-response-data';

export interface FinaticResponseTokenResponseData {
  /**
   * Optional error object with message, code, status, and details
   */
  error?: { [key: string]: any } | null;
  /**
   * Success payload containing data and optional meta. None when error is present.
   */
  success?: SuccessPayloadTokenResponseData | null;
  /**
   * Request trace identifier for tracking and debugging. Auto-generated if not provided.
   */
  trace_id?: string;
  /**
   * Optional array of warning objects
   */
  warning?: Array<{ [key: string]: any }> | null;
}
