/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Good till *date* - requires an explicit expiry timestamp.
 */
export interface GTDTIF {
  timeInForce: GTDTIFTimeInForceEnum;
  /**
   * ISO-8601 expiry timestamp
   */
  expireTime: string;
}

export enum GTDTIFTimeInForceEnum {
  Gtd = 'gtd',
}
