/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Legacy broker account schema matching pre-refactor JSON format.  This model uses camelCase field names to match the legacy API response format.
 */
export interface LegacyBrokerAccount {
    /**
     * Account UUID
     */
    'id': string;
    /**
     * Broker-provided account ID
     */
    'accountId': string;
    /**
     * Account number
     */
    'accountNumber'?: string | null;
    /**
     * Account name
     */
    'accountName'?: string | null;
    /**
     * Account type
     */
    'accountType'?: string | null;
    /**
     * Broker ID
     */
    'brokerId'?: string | null;
    /**
     * Broker name
     */
    'brokerName'?: string | null;
    /**
     * Institution ID
     */
    'institutionId'?: string | null;
    /**
     * Currency code
     */
    'currencyCode'?: string | null;
    /**
     * Account status
     */
    'accountStatus'?: string | null;
    /**
     * Sub account type
     */
    'subAccountType'?: string | null;
    /**
     * Account classification
     */
    'accountClassification'?: string | null;
    /**
     * Connection ID
     */
    'connectionId'?: string | null;
    /**
     * User ID
     */
    'userId'?: string | null;
    /**
     * Created at
     */
    'createdAt'?: string | null;
    /**
     * Updated at
     */
    'updatedAt'?: string | null;
    /**
     * Account created at
     */
    'accountCreatedAt'?: string | null;
    /**
     * Account updated at
     */
    'accountUpdatedAt'?: string | null;
    /**
     * Account first trade at
     */
    'accountFirstTradeAt'?: string | null;
    /**
     * Last synced at
     */
    'lastSyncedAt'?: string | null;
    /**
     * Balances synced at
     */
    'balancesSyncedAt'?: string | null;
    /**
     * Orders synced at
     */
    'ordersSyncedAt'?: string | null;
    /**
     * Positions synced at
     */
    'positionsSyncedAt'?: string | null;
}

