/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response data for MCP bearer bootstrap.
 */
export interface MCPBootstrapResponseData {
    /**
     * Short-lived MCP bearer token
     */
    'access_token': string;
    /**
     * OAuth token type
     */
    'token_type'?: string;
    /**
     * Bearer token expiration in seconds
     */
    'expires_in': number;
    /**
     * Granted scopes as a space-delimited string
     */
    'scope': string;
    /**
     * Backed API session ID in Redis
     */
    'session_id': string;
    /**
     * Company ID associated to API key
     */
    'company_id': string;
    /**
     * Token environment claim
     */
    'environment': string;
    /**
     * Bound MCP resource URI
     */
    'resource': string;
}

