/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Futures stop order with NinjaTrader-specific extras.
 */
export interface NinjaTraderFutureStopOrderPlaceQueryParams {
  [key: string]: any;

  orderType: NinjaTraderFutureStopOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: NinjaTraderFutureStopOrderPlaceQueryParamsAssetTypeEnum;
  action: NinjaTraderFutureStopOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  stopPrice: number;
  accountSpec?: string | null;
  isAutomated?: boolean;
  activationTime?: string | null;
  text?: string | null;
  pegDifference?: number | null;
}

export enum NinjaTraderFutureStopOrderPlaceQueryParamsOrderTypeEnum {
  Stop = 'stop',
}
export enum NinjaTraderFutureStopOrderPlaceQueryParamsAssetTypeEnum {
  Future = 'future',
}
export enum NinjaTraderFutureStopOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
