/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Cancel-order payload enriched with NinjaTrader-specific extras.
 */
export interface NinjaTraderOrderCancelQueryParams {
  [key: string]: any;

  /**
   * Broker-assigned order identifier
   */
  orderId: string;
  /**
   * Client order identifier (max 64 chars).  Useful for idempotency.
   */
  clOrdId?: string | null;
  /**
   * Optional custom FIX tag 50 (max 64 chars).
   */
  customTag50?: string | null;
  /**
   * ISO-8601 timestamp specifying when the cancellation becomes active.
   */
  activationTime?: string | null;
  /**
   * Must be *True* for programmatic requests.
   */
  isAutomated?: boolean | null;
}
