/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Futures stop limit order with NinjaTrader-specific extras.
 */
export interface NinjaTraderFutureStopLimitOrderPlaceQueryParams {
  [key: string]: any;

  orderType: NinjaTraderFutureStopLimitOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: NinjaTraderFutureStopLimitOrderPlaceQueryParamsAssetTypeEnum;
  action: NinjaTraderFutureStopLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  stopPrice: number;
  limitPrice: number;
  accountSpec?: string | null;
  isAutomated?: boolean;
  activationTime?: string | null;
  text?: string | null;
  pegDifference?: number | null;
}

export enum NinjaTraderFutureStopLimitOrderPlaceQueryParamsOrderTypeEnum {
  StopLimit = 'stop_limit',
}
export enum NinjaTraderFutureStopLimitOrderPlaceQueryParamsAssetTypeEnum {
  Future = 'future',
}
export enum NinjaTraderFutureStopLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
