/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationEquityLimitOrderPlaceQueryParams } from './tradestation-equity-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationEquityMarketOrderPlaceQueryParams } from './tradestation-equity-market-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationEquityStopLimitOrderPlaceQueryParams } from './tradestation-equity-stop-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationEquityStopOrderPlaceQueryParams } from './tradestation-equity-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationEquityTrailingStopOrderPlaceQueryParams } from './tradestation-equity-trailing-stop-order-place-query-params';

/**
 * @type Order4OneOf
 */
export type Order4OneOf =
  | ({ orderType: 'limit' } & TradestationEquityLimitOrderPlaceQueryParams)
  | ({ orderType: 'market' } & TradestationEquityMarketOrderPlaceQueryParams)
  | ({ orderType: 'stop' } & TradestationEquityStopOrderPlaceQueryParams)
  | ({ orderType: 'stop_limit' } & TradestationEquityStopLimitOrderPlaceQueryParams)
  | ({ orderType: 'trailing_stop' } & TradestationEquityTrailingStopOrderPlaceQueryParams);
