/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationOptionLimitOrderPlaceQueryParams } from './tradestation-option-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationOptionMarketOrderPlaceQueryParams } from './tradestation-option-market-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationOptionStopLimitOrderPlaceQueryParams } from './tradestation-option-stop-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationOptionStopOrderPlaceQueryParams } from './tradestation-option-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { TradestationOptionTrailingStopOrderPlaceQueryParams } from './tradestation-option-trailing-stop-order-place-query-params';

/**
 * @type Order4OneOf2
 */
export type Order4OneOf2 =
  | ({ orderType: 'limit' } & TradestationOptionLimitOrderPlaceQueryParams)
  | ({ orderType: 'market' } & TradestationOptionMarketOrderPlaceQueryParams)
  | ({ orderType: 'stop' } & TradestationOptionStopOrderPlaceQueryParams)
  | ({ orderType: 'stop_limit' } & TradestationOptionStopLimitOrderPlaceQueryParams)
  | ({ orderType: 'trailing_stop' } & TradestationOptionTrailingStopOrderPlaceQueryParams);
