/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Notional1 } from './notional1';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderOneOf } from './order-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderOneOf1 } from './order-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderOneOf2 } from './order-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';
// May contain unused imports in some cases
// @ts-ignore
import type { TrailPercent } from './trail-percent';
// May contain unused imports in some cases
// @ts-ignore
import type { TrailPrice } from './trail-price';

/**
 * @type Order
 */
export type Order = OrderOneOf | OrderOneOf1 | OrderOneOf2;


