/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty4 } from './orderqty4';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullEquityLimitOrderPlaceQueryParams } from './webull-equity-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullEquityMarketOrderPlaceQueryParams } from './webull-equity-market-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullEquityStopLimitOrderPlaceQueryParams } from './webull-equity-stop-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullEquityStopOrderPlaceQueryParams } from './webull-equity-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullEquityTrailingStopOrderPlaceQueryParams } from './webull-equity-trailing-stop-order-place-query-params';

/**
 * @type Order6OneOf
 */
export type Order6OneOf =
  | ({ orderType: 'limit' } & WebullEquityLimitOrderPlaceQueryParams)
  | ({ orderType: 'market' } & WebullEquityMarketOrderPlaceQueryParams)
  | ({ orderType: 'stop' } & WebullEquityStopOrderPlaceQueryParams)
  | ({ orderType: 'stop_limit' } & WebullEquityStopLimitOrderPlaceQueryParams)
  | ({ orderType: 'trailing_stop' } & WebullEquityTrailingStopOrderPlaceQueryParams);
