/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaEquityLimitOrderPlaceQueryParams } from './alpaca-equity-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaEquityMarketOrderPlaceQueryParams } from './alpaca-equity-market-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaEquityStopLimitOrderPlaceQueryParams } from './alpaca-equity-stop-limit-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaEquityStopOrderPlaceQueryParams } from './alpaca-equity-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { AlpacaEquityTrailingStopOrderPlaceQueryParams } from './alpaca-equity-trailing-stop-order-place-query-params';
// May contain unused imports in some cases
// @ts-ignore
import type { Notional1 } from './notional1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';
// May contain unused imports in some cases
// @ts-ignore
import type { TrailPercent } from './trail-percent';
// May contain unused imports in some cases
// @ts-ignore
import type { TrailPrice } from './trail-price';

/**
 * @type OrderOneOf
 */
export type OrderOneOf = { orderType: 'limit' } & AlpacaEquityLimitOrderPlaceQueryParams | { orderType: 'market' } & AlpacaEquityMarketOrderPlaceQueryParams | { orderType: 'stop' } & AlpacaEquityStopOrderPlaceQueryParams | { orderType: 'stop_limit' } & AlpacaEquityStopLimitOrderPlaceQueryParams | { orderType: 'trailing_stop' } & AlpacaEquityTrailingStopOrderPlaceQueryParams;


