/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Per-connection view of access for one company.
 */
export interface OwnerPortalCompanyGrant {
  company_id: string;
  has_access?: boolean;
  permissions?: { [key: string]: boolean };
}
