/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OwnerPortalCompanyGrant } from './owner-portal-company-grant';

/**
 * Broker connection with merged company grant rows for owner UI.
 */
export interface OwnerPortalConnection {
    'broker_id': string;
    'company_grants'?: Array<OwnerPortalCompanyGrant>;
    'connection_metadata'?: { [key: string]: any; } | null;
    'created_at'?: string | null;
    'id': string;
    'last_synced_at'?: string | null;
    'needs_reauth'?: boolean;
    'push_agent_connector_state'?: string | null;
    'push_agent_last_heartbeat_at'?: string | null;
    'requires_customer_agent'?: boolean;
    'status'?: string | null;
    'updated_at'?: string | null;
    'user_id': string;
}

