/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Company (account) that appears in the user\'s union of granted access.
 */
export interface OwnerPortalKnownCompany {
  company_id: string;
  company_name: string;
  trading_enabled?: boolean;
  logo_url?: string | null;
}
