/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OwnerPortalConnection } from './owner-portal-connection';
// May contain unused imports in some cases
// @ts-ignore
import type { OwnerPortalKnownCompany } from './owner-portal-known-company';

/**
 * Bootstrap payload after Supabase OTP in owner portal mode.
 */
export interface OwnerPortalBootstrapResponse {
  user_id: string;
  known_companies?: Array<OwnerPortalKnownCompany>;
  connections?: Array<OwnerPortalConnection>;
}
