/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request body for applying a reauth email opt-out token.
 */
export interface ReauthNotificationOptOutRequest {
  /**
   * High-entropy opt-out token from the reauth email link.
   */
  token: string;
}
