/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Per-connection reauth email notification preference state.
 */
export interface ReauthNotificationPreference {
  user_broker_connection_id: string;
  /**
   * Effective email notification preference for reauth events.
   */
  email_enabled: boolean;
  /**
   * True when no explicit preference row has been saved.
   */
  is_default: boolean;
  /**
   * Source of the current preference value.
   */
  preference_source: string;
  opted_out_at?: string | null;
  last_notified_at?: string | null;
  last_delivery_status?: string | null;
  last_delivery_at?: string | null;
}
