/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty1 } from './orderqty1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood equity stop order (requires stopPrice; triggers market order).
 */
export interface RobinhoodEquityStopOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': RobinhoodEquityStopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: RobinhoodEquityStopOrderPlaceQueryParamsAssetTypeEnum;
    'action': RobinhoodEquityStopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': Orderqty1;
    'stopPrice': number;
    /**
     * Allow trading during extended hours (premium users only)
     */
    'extendedHours'?: boolean;
    /**
     * Market hours to trade in
     */
    'marketHours'?: RobinhoodEquityStopOrderPlaceQueryParamsMarketHoursEnum;
}

export enum RobinhoodEquityStopOrderPlaceQueryParamsOrderTypeEnum {
    Stop = 'stop'
}
export enum RobinhoodEquityStopOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum RobinhoodEquityStopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum RobinhoodEquityStopOrderPlaceQueryParamsMarketHoursEnum {
    RegularHours = 'regular_hours',
    AllDayHours = 'all_day_hours',
    ExtendedHours = 'extended_hours'
}


