/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty1 } from './orderqty1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood equity market order (no price; executes at best available).
 */
export interface RobinhoodEquityMarketOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': RobinhoodEquityMarketOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: RobinhoodEquityMarketOrderPlaceQueryParamsAssetTypeEnum;
    'action': RobinhoodEquityMarketOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': Orderqty1;
    /**
     * Allow trading during extended hours (premium users only)
     */
    'extendedHours'?: boolean;
    /**
     * Market hours to trade in
     */
    'marketHours'?: RobinhoodEquityMarketOrderPlaceQueryParamsMarketHoursEnum;
}

export enum RobinhoodEquityMarketOrderPlaceQueryParamsOrderTypeEnum {
    Market = 'market'
}
export enum RobinhoodEquityMarketOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum RobinhoodEquityMarketOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum RobinhoodEquityMarketOrderPlaceQueryParamsMarketHoursEnum {
    RegularHours = 'regular_hours',
    AllDayHours = 'all_day_hours',
    ExtendedHours = 'extended_hours'
}


