/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RobinhoodOptionSpreadLeg } from './robinhood-option-spread-leg';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood option limit order (requires price; single-leg or spread).
 */
export interface RobinhoodOptionLimitOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': RobinhoodOptionLimitOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: RobinhoodOptionLimitOrderPlaceQueryParamsAssetTypeEnum;
    'action': RobinhoodOptionLimitOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': number;
    'price': number;
    /**
     * Direction for option spread orders (debit/credit)
     */
    'direction'?: RobinhoodOptionLimitOrderPlaceQueryParamsDirectionEnum | null;
    /**
     * Spread legs for order_option_spread()
     */
    'spread'?: Array<RobinhoodOptionSpreadLeg> | null;
    /**
     * Position effect for single-leg option orders
     */
    'positionEffect'?: RobinhoodOptionLimitOrderPlaceQueryParamsPositionEffectEnum | null;
    /**
     * Credit or debit for single-leg option orders
     */
    'creditOrDebit'?: RobinhoodOptionLimitOrderPlaceQueryParamsCreditOrDebitEnum | null;
    /**
     * Option expiration date (YYYY-MM-DD format)
     */
    'expirationDate'?: string | null;
    /**
     * Option strike price
     */
    'strikePrice'?: number | null;
    /**
     * Option type (call/put/both)
     */
    'optionType'?: RobinhoodOptionLimitOrderPlaceQueryParamsOptionTypeEnum | null;
}

export enum RobinhoodOptionLimitOrderPlaceQueryParamsOrderTypeEnum {
    Limit = 'limit'
}
export enum RobinhoodOptionLimitOrderPlaceQueryParamsAssetTypeEnum {
    EquityOption = 'equity_option'
}
export enum RobinhoodOptionLimitOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum RobinhoodOptionLimitOrderPlaceQueryParamsDirectionEnum {
    Debit = 'debit',
    Credit = 'credit'
}
export enum RobinhoodOptionLimitOrderPlaceQueryParamsPositionEffectEnum {
    Open = 'open',
    Close = 'close'
}
export enum RobinhoodOptionLimitOrderPlaceQueryParamsCreditOrDebitEnum {
    Debit = 'debit',
    Credit = 'credit'
}
export enum RobinhoodOptionLimitOrderPlaceQueryParamsOptionTypeEnum {
    Call = 'call',
    Put = 'put',
    Both = 'both'
}


