/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty2 } from './orderqty2';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood crypto limit order (requires price).
 */
export interface RobinhoodCryptoLimitOrderPlaceQueryParams {
  [key: string]: any;

  orderType: RobinhoodCryptoLimitOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: RobinhoodCryptoLimitOrderPlaceQueryParamsAssetTypeEnum;
  action: RobinhoodCryptoLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: Orderqty2;
  price: number;
  /**
   * Whether quantityOrPrice represents quantity or price
   */
  amountIn?: RobinhoodCryptoLimitOrderPlaceQueryParamsAmountInEnum;
}

export enum RobinhoodCryptoLimitOrderPlaceQueryParamsOrderTypeEnum {
  Limit = 'limit',
}
export enum RobinhoodCryptoLimitOrderPlaceQueryParamsAssetTypeEnum {
  Crypto = 'crypto',
}
export enum RobinhoodCryptoLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum RobinhoodCryptoLimitOrderPlaceQueryParamsAmountInEnum {
  Quantity = 'quantity',
  Price = 'price',
}
