/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty1 } from './orderqty1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood equity trailing stop order (stopPrice trails market).
 */
export interface RobinhoodEquityTrailingStopOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': RobinhoodEquityTrailingStopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: RobinhoodEquityTrailingStopOrderPlaceQueryParamsAssetTypeEnum;
    'action': RobinhoodEquityTrailingStopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': Orderqty1;
    'stopPrice': number;
    'trailPercent'?: number | null;
    'trailPrice'?: number | null;
    /**
     * Allow trading during extended hours (premium users only)
     */
    'extendedHours'?: boolean;
    /**
     * Market hours to trade in
     */
    'marketHours'?: RobinhoodEquityTrailingStopOrderPlaceQueryParamsMarketHoursEnum;
}

export enum RobinhoodEquityTrailingStopOrderPlaceQueryParamsOrderTypeEnum {
    TrailingStop = 'trailing_stop'
}
export enum RobinhoodEquityTrailingStopOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum RobinhoodEquityTrailingStopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum RobinhoodEquityTrailingStopOrderPlaceQueryParamsMarketHoursEnum {
    RegularHours = 'regular_hours',
    AllDayHours = 'all_day_hours',
    ExtendedHours = 'extended_hours'
}


