/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber } from './accountnumber';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderModifyQueryParamsBase } from './order-modify-query-params-base';

/**
 * Robinhood modify-order request body (partial update).  Attributes ---------- broker : Literal[\"robinhood\"]     Discriminator; must be ``\"robinhood\"``. account_number : str | int     Broker-provided account number (top-level). Serialized as ``accountNumber``. order : OrderModifyQueryParamsBase     Delta of fields to change; backend merges with existing order.  Notes ----- Uses ``extra=\"forbid\"`` and ``populate_by_name=True``.
 */
export interface RobinhoodOrderModifyRequest {
    'broker': RobinhoodOrderModifyRequestBrokerEnum;
    'accountNumber': Accountnumber;
    'order': OrderModifyQueryParamsBase;
}

export enum RobinhoodOrderModifyRequestBrokerEnum {
    Robinhood = 'robinhood'
}


