/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty2 } from './orderqty2';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood crypto stop order (requires stopPrice).
 */
export interface RobinhoodCryptoStopOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': RobinhoodCryptoStopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: RobinhoodCryptoStopOrderPlaceQueryParamsAssetTypeEnum;
    'action': RobinhoodCryptoStopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': Orderqty2;
    'stopPrice': number;
    /**
     * Whether quantityOrPrice represents quantity or price
     */
    'amountIn'?: RobinhoodCryptoStopOrderPlaceQueryParamsAmountInEnum;
}

export enum RobinhoodCryptoStopOrderPlaceQueryParamsOrderTypeEnum {
    Stop = 'stop'
}
export enum RobinhoodCryptoStopOrderPlaceQueryParamsAssetTypeEnum {
    Crypto = 'crypto'
}
export enum RobinhoodCryptoStopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum RobinhoodCryptoStopOrderPlaceQueryParamsAmountInEnum {
    Quantity = 'quantity',
    Price = 'price'
}


