/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BrokerDataOptionTypeEnum } from './broker-data-option-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { BrokerDataOrderSideEnum } from './broker-data-order-side-enum';

/**
 * One leg within a multi-leg option spread order.  Represents a single leg in an option spread (e.g., vertical, calendar, iron condor). Used by order_option_spread() in the Robinhood SDK and matches the structure expected by the raw query params layer for transformation to Robinhood REST API format.  Attributes ---------- expiration_date : str     Option expiration date in YYYY-MM-DD format. Serialized as     ``expirationDate``. strike : float     Strike price for the option leg. Serialized as ``strikePrice``. option_type : BrokerDataOptionTypeEnum     Option type (call or put). Serialized as ``optionType``. effect : Literal[\"open\", \"close\"]     Position effect for the leg. Serialized as ``positionEffect``. action : BrokerDataOrderSideEnum     Order side (buy or sell) for the leg. ratio_quantity : int, optional     Ratio quantity for the leg in multi-leg spreads. Default is 1.     Serialized as ``ratioQuantity``.  See Also -------- RobinhoodOptionOrderPlaceQueryParamsUnionBase : Parent model that uses     spread legs for order_option_spread().
 */
export interface RobinhoodOptionSpreadLeg {
  expirationDate: string;
  strikePrice: number;
  optionType: BrokerDataOptionTypeEnum;
  positionEffect: RobinhoodOptionSpreadLegPositionEffectEnum;
  action: BrokerDataOrderSideEnum;
  ratioQuantity?: number;
}

export enum RobinhoodOptionSpreadLegPositionEffectEnum {
  Open = 'open',
  Close = 'close',
}
