/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RobinhoodOptionSpreadLeg } from './robinhood-option-spread-leg';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Robinhood option market order (no price; executes at best available).
 */
export interface RobinhoodOptionMarketOrderPlaceQueryParams {
  [key: string]: any;

  orderType: RobinhoodOptionMarketOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: RobinhoodOptionMarketOrderPlaceQueryParamsAssetTypeEnum;
  action: RobinhoodOptionMarketOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: number;
  /**
   * Direction for option spread orders (debit/credit)
   */
  direction?: RobinhoodOptionMarketOrderPlaceQueryParamsDirectionEnum | null;
  /**
   * Spread legs for order_option_spread()
   */
  spread?: Array<RobinhoodOptionSpreadLeg> | null;
  /**
   * Position effect for single-leg option orders
   */
  positionEffect?: RobinhoodOptionMarketOrderPlaceQueryParamsPositionEffectEnum | null;
  /**
   * Credit or debit for single-leg option orders
   */
  creditOrDebit?: RobinhoodOptionMarketOrderPlaceQueryParamsCreditOrDebitEnum | null;
  /**
   * Option expiration date (YYYY-MM-DD format)
   */
  expirationDate?: string | null;
  /**
   * Option strike price
   */
  strikePrice?: number | null;
  /**
   * Option type (call/put/both)
   */
  optionType?: RobinhoodOptionMarketOrderPlaceQueryParamsOptionTypeEnum | null;
}

export enum RobinhoodOptionMarketOrderPlaceQueryParamsOrderTypeEnum {
  Market = 'market',
}
export enum RobinhoodOptionMarketOrderPlaceQueryParamsAssetTypeEnum {
  EquityOption = 'equity_option',
}
export enum RobinhoodOptionMarketOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum RobinhoodOptionMarketOrderPlaceQueryParamsDirectionEnum {
  Debit = 'debit',
  Credit = 'credit',
}
export enum RobinhoodOptionMarketOrderPlaceQueryParamsPositionEffectEnum {
  Open = 'open',
  Close = 'close',
}
export enum RobinhoodOptionMarketOrderPlaceQueryParamsCreditOrDebitEnum {
  Debit = 'debit',
  Credit = 'credit',
}
export enum RobinhoodOptionMarketOrderPlaceQueryParamsOptionTypeEnum {
  Call = 'call',
  Put = 'put',
  Both = 'both',
}
