/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Cancel order query params for Robinhood.  **NOTE:** This file is a template and was auto-generated. You must review and tailor the fields to pull from the full JSON query params model in the `src/finatic_core/brokers/robinhood/executors/raw/robinhood_order_cancel_raw_query_params.py` file.  The goal is to offer a type-safe yet convenient schema that callers can use without worrying about the full raw REST payload - the executor layer will translate this higher-level model into the wire-level counterpart defined in `executors/raw/robinhood_order_cancel_raw_query_params.py`.  Extends the core OrderCancelQueryParams with asset_type for routing to the correct cancel function. The order_id field is inherited from the core model.  Matches the function signatures: - cancel_stock_order(orderID): Cancel a specific order - cancel_option_order(orderID): Cancel a specific option order - cancel_crypto_order(orderID): Cancel a specific crypto order
 */
export interface RobinhoodOrderCancelQueryParams {
  /**
   * Broker-assigned order identifier
   */
  orderId: string;
  /**
   * Asset type for routing to correct cancel function (EQUITY, EQUITY_OPTION, or CRYPTO)
   */
  assetType?: RobinhoodOrderCancelQueryParamsAssetTypeEnum;
}

export enum RobinhoodOrderCancelQueryParamsAssetTypeEnum {
  Equity = 'equity',
  EquityOption = 'equity_option',
  Crypto = 'crypto',
}
