/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Crypto stop order with Robinhood-specific extras.
 */
export interface RobinhoodCryptoStopOrderPlaceQueryParams {
  [key: string]: any;

  orderType: RobinhoodCryptoStopOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: RobinhoodCryptoStopOrderPlaceQueryParamsAssetTypeEnum;
  action: RobinhoodCryptoStopOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  stopPrice: number;
  /**
   * Whether quantityOrPrice represents quantity or price
   */
  amountIn?: RobinhoodCryptoStopOrderPlaceQueryParamsAmountInEnum;
}

export enum RobinhoodCryptoStopOrderPlaceQueryParamsOrderTypeEnum {
  Stop = 'stop',
}
export enum RobinhoodCryptoStopOrderPlaceQueryParamsAssetTypeEnum {
  Crypto = 'crypto',
}
export enum RobinhoodCryptoStopOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum RobinhoodCryptoStopOrderPlaceQueryParamsAmountInEnum {
  Quantity = 'quantity',
  Price = 'price',
}
