/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Equity stop limit order with Robinhood-specific extras.
 */
export interface RobinhoodEquityStopLimitOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': RobinhoodEquityStopLimitOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: RobinhoodEquityStopLimitOrderPlaceQueryParamsAssetTypeEnum;
    'action': RobinhoodEquityStopLimitOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce1;
    'symbol': string;
    'orderQty': number;
    'stopPrice': number;
    'limitPrice': number;
    /**
     * Allow trading during extended hours (premium users only)
     */
    'extendedHours'?: boolean;
    /**
     * Market hours to trade in
     */
    'marketHours'?: RobinhoodEquityStopLimitOrderPlaceQueryParamsMarketHoursEnum;
}

export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsOrderTypeEnum {
    StopLimit = 'stop_limit'
}
export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum RobinhoodEquityStopLimitOrderPlaceQueryParamsMarketHoursEnum {
    RegularHours = 'regular_hours',
    AllDayHours = 'all_day_hours',
    ExtendedHours = 'extended_hours'
}


