/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionStatus } from './session-status';

/**
 * Response data for session operations.
 */
export interface SessionResponseData {
    /**
     * Company ID
     */
    'company_id': string;
    /**
     * Session expiration time
     */
    'expires_at': string;
    /**
     * True when a valid provisional user_id was applied: trading/data may proceed, but portal connection-management still requires link-user / OTP step-up.
     */
    'portal_connection_management_pending'?: boolean;
    /**
     * True when a provisional user_id was supplied on start but was not applied (invalid UUID or no broker connection with company access for this company).
     */
    'provided_user_id_rejected'?: boolean;
    /**
     * Session ID
     */
    'session_id': string;
    /**
     * Session status
     */
    'status': SessionStatus;
    /**
     * User ID if authenticated
     */
    'user_id'?: string | null;
}



