/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FDXBrokerPositionLotFill } from './fdxbroker-position-lot-fill';

export interface SuccessPayloadListFDXBrokerPositionLotFill {
  _id?: string;
  data?: Array<FDXBrokerPositionLotFill> | null;
  meta?: { [key: string]: any } | null;
}
