/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Equity market order with TastyTrade extras.
 */
export interface TastyTradeEquityMarketOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': TastyTradeEquityMarketOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: TastyTradeEquityMarketOrderPlaceQueryParamsAssetTypeEnum;
    'action': TastyTradeEquityMarketOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce1;
    'symbol': string;
    'orderQty': number;
    'automated-source'?: boolean;
    'price-effect'?: TastyTradeEquityMarketOrderPlaceQueryParamsPriceEffectEnum | null;
    'external-identifier'?: string | null;
    'partition-key'?: string | null;
    'preflight-id'?: string | null;
    'source'?: string | null;
    'value-effect'?: TastyTradeEquityMarketOrderPlaceQueryParamsValueEffectEnum | null;
}

export enum TastyTradeEquityMarketOrderPlaceQueryParamsOrderTypeEnum {
    Market = 'market'
}
export enum TastyTradeEquityMarketOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum TastyTradeEquityMarketOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum TastyTradeEquityMarketOrderPlaceQueryParamsPriceEffectEnum {
    Debit = 'Debit',
    Credit = 'Credit'
}
export enum TastyTradeEquityMarketOrderPlaceQueryParamsValueEffectEnum {
    Debit = 'Debit',
    Credit = 'Credit'
}


