/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber2 } from './accountnumber2';

/**
 * Cancel-order payload enriched with TastyTrade-specific *account_number*.  Notes ----- *account_number* is optional in the request body. The top-level *accountNumber* from the request is passed through the call chain (broker_service → broker → executor) and used by the executor to build the DELETE URL ``/accounts/{account_number}/orders/{order_id}``. This field remains for backward compatibility but is typically not needed in the nested ``order`` object.
 */
export interface TastyTradeOrderCancelQueryParams {
    /**
     * Broker-assigned order identifier
     */
    'orderId': string;
    'accountNumber'?: Accountnumber2 | null;
}

