/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Option stop order with TastyTrade extras.
 */
export interface TastyTradeOptionStopOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': TastyTradeOptionStopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: TastyTradeOptionStopOrderPlaceQueryParamsAssetTypeEnum;
    'action': TastyTradeOptionStopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': number;
    'stopPrice': number;
    'automated-source'?: boolean;
    'price-effect'?: TastyTradeOptionStopOrderPlaceQueryParamsPriceEffectEnum | null;
    'external-identifier'?: string | null;
    'partition-key'?: string | null;
    'preflight-id'?: string | null;
    'source'?: string | null;
    'value-effect'?: TastyTradeOptionStopOrderPlaceQueryParamsValueEffectEnum | null;
    /**
     * Option expiration date (YYYY-MM-DD format).
     */
    'expirationDate': string;
    /**
     * Option strike price.
     */
    'strikePrice': number;
    /**
     * Option type (call or put).
     */
    'optionType': TastyTradeOptionStopOrderPlaceQueryParamsOptionTypeEnum;
    /**
     * Position effect for the option leg.
     */
    'positionEffect'?: TastyTradeOptionStopOrderPlaceQueryParamsPositionEffectEnum;
}

export enum TastyTradeOptionStopOrderPlaceQueryParamsOrderTypeEnum {
    Stop = 'stop'
}
export enum TastyTradeOptionStopOrderPlaceQueryParamsAssetTypeEnum {
    EquityOption = 'equity_option'
}
export enum TastyTradeOptionStopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum TastyTradeOptionStopOrderPlaceQueryParamsPriceEffectEnum {
    Debit = 'Debit',
    Credit = 'Credit'
}
export enum TastyTradeOptionStopOrderPlaceQueryParamsValueEffectEnum {
    Debit = 'Debit',
    Credit = 'Credit'
}
export enum TastyTradeOptionStopOrderPlaceQueryParamsOptionTypeEnum {
    Call = 'call',
    Put = 'put'
}
export enum TastyTradeOptionStopOrderPlaceQueryParamsPositionEffectEnum {
    Open = 'open',
    Close = 'close'
}


