/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Option market order with TastyTrade extras.
 */
export interface TastyTradeOptionMarketOrderPlaceQueryParams {
  [key: string]: any;

  orderType: TastyTradeOptionMarketOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: TastyTradeOptionMarketOrderPlaceQueryParamsAssetTypeEnum;
  action: TastyTradeOptionMarketOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  'automated-source'?: boolean;
  'price-effect'?: TastyTradeOptionMarketOrderPlaceQueryParamsPriceEffectEnum | null;
  'external-identifier'?: string | null;
  'partition-key'?: string | null;
  'preflight-id'?: string | null;
  source?: string | null;
  'value-effect'?: TastyTradeOptionMarketOrderPlaceQueryParamsValueEffectEnum | null;
  /**
   * Option expiration date (YYYY-MM-DD format).
   */
  expirationDate: string;
  /**
   * Option strike price.
   */
  strikePrice: number;
  /**
   * Option type (call or put).
   */
  optionType: TastyTradeOptionMarketOrderPlaceQueryParamsOptionTypeEnum;
  /**
   * Position effect for the option leg.
   */
  positionEffect?: TastyTradeOptionMarketOrderPlaceQueryParamsPositionEffectEnum;
}

export enum TastyTradeOptionMarketOrderPlaceQueryParamsOrderTypeEnum {
  Market = 'market',
}
export enum TastyTradeOptionMarketOrderPlaceQueryParamsAssetTypeEnum {
  EquityOption = 'equity_option',
}
export enum TastyTradeOptionMarketOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum TastyTradeOptionMarketOrderPlaceQueryParamsPriceEffectEnum {
  Debit = 'Debit',
  Credit = 'Credit',
}
export enum TastyTradeOptionMarketOrderPlaceQueryParamsValueEffectEnum {
  Debit = 'Debit',
  Credit = 'Credit',
}
export enum TastyTradeOptionMarketOrderPlaceQueryParamsOptionTypeEnum {
  Call = 'call',
  Put = 'put',
}
export enum TastyTradeOptionMarketOrderPlaceQueryParamsPositionEffectEnum {
  Open = 'open',
  Close = 'close',
}
