/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Option trailing stop order with TastyTrade extras.
 */
export interface TastyTradeOptionTrailingStopOrderPlaceQueryParams {
  [key: string]: any;

  orderType: TastyTradeOptionTrailingStopOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: TastyTradeOptionTrailingStopOrderPlaceQueryParamsAssetTypeEnum;
  action: TastyTradeOptionTrailingStopOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: number;
  stopPrice: number;
  trailPercent?: number | null;
  trailPrice?: number | null;
  'automated-source'?: boolean;
  'price-effect'?: TastyTradeOptionTrailingStopOrderPlaceQueryParamsPriceEffectEnum | null;
  'external-identifier'?: string | null;
  'partition-key'?: string | null;
  'preflight-id'?: string | null;
  source?: string | null;
  'value-effect'?: TastyTradeOptionTrailingStopOrderPlaceQueryParamsValueEffectEnum | null;
  /**
   * Option expiration date (YYYY-MM-DD format).
   */
  expirationDate: string;
  /**
   * Option strike price.
   */
  strikePrice: number;
  /**
   * Option type (call or put).
   */
  optionType: TastyTradeOptionTrailingStopOrderPlaceQueryParamsOptionTypeEnum;
  /**
   * Position effect for the option leg.
   */
  positionEffect?: TastyTradeOptionTrailingStopOrderPlaceQueryParamsPositionEffectEnum;
}

export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsOrderTypeEnum {
  TrailingStop = 'trailing_stop',
}
export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsAssetTypeEnum {
  EquityOption = 'equity_option',
}
export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsPriceEffectEnum {
  Debit = 'Debit',
  Credit = 'Credit',
}
export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsValueEffectEnum {
  Debit = 'Debit',
  Credit = 'Credit',
}
export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsOptionTypeEnum {
  Call = 'call',
  Put = 'put',
}
export enum TastyTradeOptionTrailingStopOrderPlaceQueryParamsPositionEffectEnum {
  Open = 'open',
  Close = 'close',
}
