/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response data for token operations.
 */
export interface TokenResponseData {
    /**
     * Token expiration time
     */
    'expires_at': string;
    /**
     * One-time use token
     */
    'one_time_token': string;
}

