/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Consumer params for Trading212 market order placement.  Market orders are executed immediately at the best available price. Extended hours trading is supported.
 */
export interface Trading212MarketOrderPlaceQueryParams {
  [key: string]: any;

  /**
   * Allow execution outside regular trading hours (market orders only)
   */
  extendedHours?: boolean;
  orderType: Trading212MarketOrderPlaceQueryParamsOrderTypeEnum;
  assetType: Trading212MarketOrderPlaceQueryParamsAssetTypeEnum;
  action: Trading212MarketOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
}

export enum Trading212MarketOrderPlaceQueryParamsOrderTypeEnum {
  Market = 'market',
}
export enum Trading212MarketOrderPlaceQueryParamsAssetTypeEnum {
  Equity = 'equity',
  EquityOption = 'equity_option',
  Crypto = 'crypto',
  Forex = 'forex',
  Future = 'future',
  FutureOption = 'future_option',
  Bond = 'bond',
}
export enum Trading212MarketOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
