/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Equity limit order with TradeStation-specific extras.
 */
export interface TradestationEquityLimitOrderPlaceQueryParams {
  [key: string]: any;

  orderType: TradestationEquityLimitOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: TradestationEquityLimitOrderPlaceQueryParamsAssetTypeEnum;
  action: TradestationEquityLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  price: number;
  accountId?: string | null;
}

export enum TradestationEquityLimitOrderPlaceQueryParamsOrderTypeEnum {
  Limit = 'limit',
}
export enum TradestationEquityLimitOrderPlaceQueryParamsAssetTypeEnum {
  Equity = 'equity',
}
export enum TradestationEquityLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
