/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Equity stop limit order with TradeStation-specific extras.
 */
export interface TradestationEquityStopLimitOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': TradestationEquityStopLimitOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: TradestationEquityStopLimitOrderPlaceQueryParamsAssetTypeEnum;
    'action': TradestationEquityStopLimitOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': number;
    'stopPrice': number;
    'limitPrice': number;
    'accountId'?: string | null;
}

export enum TradestationEquityStopLimitOrderPlaceQueryParamsOrderTypeEnum {
    StopLimit = 'stop_limit'
}
export enum TradestationEquityStopLimitOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum TradestationEquityStopLimitOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


