/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Equity trailing stop order with TradeStation-specific extras.
 */
export interface TradestationEquityTrailingStopOrderPlaceQueryParams {
  [key: string]: any;

  orderType: TradestationEquityTrailingStopOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: TradestationEquityTrailingStopOrderPlaceQueryParamsAssetTypeEnum;
  action: TradestationEquityTrailingStopOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: number;
  stopPrice: number;
  trailPercent?: number | null;
  trailPrice?: number | null;
  accountId?: string | null;
}

export enum TradestationEquityTrailingStopOrderPlaceQueryParamsOrderTypeEnum {
  TrailingStop = 'trailing_stop',
}
export enum TradestationEquityTrailingStopOrderPlaceQueryParamsAssetTypeEnum {
  Equity = 'equity',
}
export enum TradestationEquityTrailingStopOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
