/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Equity stop order with TradeStation-specific extras.
 */
export interface TradestationEquityStopOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': TradestationEquityStopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: TradestationEquityStopOrderPlaceQueryParamsAssetTypeEnum;
    'action': TradestationEquityStopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce1;
    'symbol': string;
    'orderQty': number;
    'stopPrice': number;
    'accountId'?: string | null;
}

export enum TradestationEquityStopOrderPlaceQueryParamsOrderTypeEnum {
    Stop = 'stop'
}
export enum TradestationEquityStopOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum TradestationEquityStopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


