/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Option stop limit order with TradeStation-specific extras.
 */
export interface TradestationOptionStopLimitOrderPlaceQueryParams {
  [key: string]: any;

  orderType: TradestationOptionStopLimitOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: TradestationOptionStopLimitOrderPlaceQueryParamsAssetTypeEnum;
  action: TradestationOptionStopLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  stopPrice: number;
  limitPrice: number;
  accountId?: string | null;
  route?: string | null;
  optionRouteKind?: TradestationOptionStopLimitOrderPlaceQueryParamsOptionRouteKindEnum | null;
}

export enum TradestationOptionStopLimitOrderPlaceQueryParamsOrderTypeEnum {
  StopLimit = 'stop_limit',
}
export enum TradestationOptionStopLimitOrderPlaceQueryParamsAssetTypeEnum {
  EquityOption = 'equity_option',
}
export enum TradestationOptionStopLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum TradestationOptionStopLimitOrderPlaceQueryParamsOptionRouteKindEnum {
  StockOption = 'stock_option',
  IndexOption = 'index_option',
}
