/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Consumer params for Trading212 stop order placement.  Stop orders trigger a market order when the stop price is reached. The stop price is triggered by the Last Traded Price (LTP).
 */
export interface Trading212StopOrderPlaceQueryParams {
    [key: string]: any;

    /**
     * Allow execution outside regular trading hours (market orders only)
     */
    'extendedHours'?: boolean;
    'orderType': Trading212StopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType': Trading212StopOrderPlaceQueryParamsAssetTypeEnum;
    'action': Trading212StopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce1;
    'symbol': string;
    'orderQty': number;
    'stopPrice': number;
}

export enum Trading212StopOrderPlaceQueryParamsOrderTypeEnum {
    Stop = 'stop'
}
export enum Trading212StopOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity',
    EquityOption = 'equity_option',
    Crypto = 'crypto',
    Forex = 'forex',
    Future = 'future',
    FutureOption = 'future_option',
    Bond = 'bond'
}
export enum Trading212StopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}


