/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty4 } from './orderqty4';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Equity stop (stop loss) order for Webull OAuth.
 */
export interface WebullEquityStopOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': WebullEquityStopOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: WebullEquityStopOrderPlaceQueryParamsAssetTypeEnum;
    'action': WebullEquityStopOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': Orderqty4;
    'stopPrice': number;
    /**
     * Extended hours: N=regular only, Y=pre/post market
     */
    'supportTradingSession'?: WebullEquityStopOrderPlaceQueryParamsSupportTradingSessionEnum | null;
    /**
     * When true, allow pre/post market. Used when supportTradingSession not set.
     */
    'extendedHours'?: boolean | null;
    /**
     * Idempotency key; server generates if omitted
     */
    'clientOrderId'?: string | null;
}

export enum WebullEquityStopOrderPlaceQueryParamsOrderTypeEnum {
    Stop = 'stop'
}
export enum WebullEquityStopOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum WebullEquityStopOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum WebullEquityStopOrderPlaceQueryParamsSupportTradingSessionEnum {
    Y = 'Y',
    N = 'N'
}


