/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty4 } from './orderqty4';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Equity trailing stop order for Webull OAuth.
 */
export interface WebullEquityTrailingStopOrderPlaceQueryParams {
  [key: string]: any;

  orderType: WebullEquityTrailingStopOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: WebullEquityTrailingStopOrderPlaceQueryParamsAssetTypeEnum;
  action: WebullEquityTrailingStopOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: Orderqty4;
  stopPrice: number;
  trailPercent?: number | null;
  trailPrice?: number | null;
  /**
   * Extended hours: N=regular only, Y=pre/post market
   */
  supportTradingSession?: WebullEquityTrailingStopOrderPlaceQueryParamsSupportTradingSessionEnum | null;
  /**
   * When true, allow pre/post market. Used when supportTradingSession not set.
   */
  extendedHours?: boolean | null;
  /**
   * Idempotency key; server generates if omitted
   */
  clientOrderId?: string | null;
}

export enum WebullEquityTrailingStopOrderPlaceQueryParamsOrderTypeEnum {
  TrailingStop = 'trailing_stop',
}
export enum WebullEquityTrailingStopOrderPlaceQueryParamsAssetTypeEnum {
  Equity = 'equity',
}
export enum WebullEquityTrailingStopOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum WebullEquityTrailingStopOrderPlaceQueryParamsSupportTradingSessionEnum {
  Y = 'Y',
  N = 'N',
}
