/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BrokerDataOptionTypeEnum } from './broker-data-option-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { Strikeprice1 } from './strikeprice1';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce1 } from './timeinforce1';

/**
 * Webull single-leg option limit order.
 */
export interface WebullOptionLimitOrderPlaceQueryParams {
  [key: string]: any;

  orderType: WebullOptionLimitOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: WebullOptionLimitOrderPlaceQueryParamsAssetTypeEnum;
  action: WebullOptionLimitOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce1;
  symbol: string;
  orderQty: number;
  price: number;
  supportTradingSession?: WebullOptionLimitOrderPlaceQueryParamsSupportTradingSessionEnum | null;
  clientOrderId?: string | null;
  expirationDate: string;
  strikePrice: Strikeprice1;
  optionType: BrokerDataOptionTypeEnum;
  positionEffect?: string | null;
  creditOrDebit?: string | null;
}

export enum WebullOptionLimitOrderPlaceQueryParamsOrderTypeEnum {
  Limit = 'limit',
}
export enum WebullOptionLimitOrderPlaceQueryParamsAssetTypeEnum {
  EquityOption = 'equity_option',
}
export enum WebullOptionLimitOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum WebullOptionLimitOrderPlaceQueryParamsSupportTradingSessionEnum {
  Y = 'Y',
  N = 'N',
}
