/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Accountnumber } from './accountnumber';
// May contain unused imports in some cases
// @ts-ignore
import type { WebullOrderCancelQueryParams } from './webull-order-cancel-query-params';

/**
 * Webull cancel-order request body.  Attributes ---------- broker : Literal[\"webull\"]     Discriminator; must be ``\"webull\"``. account_number : str | int     Broker-provided account number (top-level). Serialized as ``accountNumber``. order : WebullOrderCancelQueryParams     Webull cancel parameters (client_order_id).  Notes ----- Uses ``extra=\"forbid\"`` and ``populate_by_name=True``.
 */
export interface WebullOrderCancelRequest {
  broker: WebullOrderCancelRequestBrokerEnum;
  accountNumber: Accountnumber;
  order: WebullOrderCancelQueryParams;
}

export enum WebullOrderCancelRequestBrokerEnum {
  Webull = 'webull',
}
