/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrderModifyQueryParamsBaseTimeInForce } from './order-modify-query-params-base-time-in-force';

export interface WebullTrailingStopOrderModifyQueryParams {
  orderQty?: number | null;
  orderId?: string | null;
  orderType: WebullTrailingStopOrderModifyQueryParamsOrderTypeEnum;
  assetType?: WebullTrailingStopOrderModifyQueryParamsAssetTypeEnum | null;
  timeInForce?: OrderModifyQueryParamsBaseTimeInForce | null;
  isAutomated?: boolean | null;
  price?: number | null;
  stopPrice: number;
}

export enum WebullTrailingStopOrderModifyQueryParamsOrderTypeEnum {
  TrailingStop = 'trailing_stop',
}
export enum WebullTrailingStopOrderModifyQueryParamsAssetTypeEnum {
  Equity = 'equity',
  EquityOption = 'equity_option',
  Crypto = 'crypto',
  Forex = 'forex',
  Future = 'future',
  FutureOption = 'future_option',
  Bond = 'bond',
}
