/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty4 } from './orderqty4';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Equity market order for Webull OAuth.
 */
export interface WebullEquityMarketOrderPlaceQueryParams {
  [key: string]: any;

  orderType: WebullEquityMarketOrderPlaceQueryParamsOrderTypeEnum;
  assetType?: WebullEquityMarketOrderPlaceQueryParamsAssetTypeEnum;
  action: WebullEquityMarketOrderPlaceQueryParamsActionEnum;
  timeInForce: Timeinforce;
  symbol: string;
  orderQty: Orderqty4;
  /**
   * Extended hours: N=regular only, Y=pre/post market
   */
  supportTradingSession?: WebullEquityMarketOrderPlaceQueryParamsSupportTradingSessionEnum | null;
  /**
   * When true, allow pre/post market. Used when supportTradingSession not set.
   */
  extendedHours?: boolean | null;
  /**
   * Idempotency key; server generates if omitted
   */
  clientOrderId?: string | null;
}

export enum WebullEquityMarketOrderPlaceQueryParamsOrderTypeEnum {
  Market = 'market',
}
export enum WebullEquityMarketOrderPlaceQueryParamsAssetTypeEnum {
  Equity = 'equity',
}
export enum WebullEquityMarketOrderPlaceQueryParamsActionEnum {
  Buy = 'buy',
  Sell = 'sell',
}
export enum WebullEquityMarketOrderPlaceQueryParamsSupportTradingSessionEnum {
  Y = 'Y',
  N = 'N',
}
