/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderModifyQueryParamsBaseTimeInForce } from './order-modify-query-params-base-time-in-force';

export interface WebullLimitOrderModifyQueryParams {
    'orderQty'?: number | null;
    /**
     * Broker-assigned order identifier
     */
    'orderId'?: string | null;
    'orderType': WebullLimitOrderModifyQueryParamsOrderTypeEnum;
    'assetType'?: WebullLimitOrderModifyQueryParamsAssetTypeEnum | null;
    'timeInForce'?: OrderModifyQueryParamsBaseTimeInForce | null;
    /**
     * Indicates algorithmic/automated order source (optional)
     */
    'isAutomated'?: boolean | null;
    'price': number;
    'stopPrice'?: number | null;
}

export enum WebullLimitOrderModifyQueryParamsOrderTypeEnum {
    Limit = 'limit'
}
export enum WebullLimitOrderModifyQueryParamsAssetTypeEnum {
    Equity = 'equity',
    EquityOption = 'equity_option',
    Crypto = 'crypto',
    Forex = 'forex',
    Future = 'future',
    FutureOption = 'future_option',
    Bond = 'bond'
}


