/* tslint:disable */
/* eslint-disable */
/**
 * Finatic FastAPI Backend
 * FinaticAPI REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Orderqty4 } from './orderqty4';
// May contain unused imports in some cases
// @ts-ignore
import type { Timeinforce } from './timeinforce';

/**
 * Equity limit order for Webull OAuth.
 */
export interface WebullEquityLimitOrderPlaceQueryParams {
    [key: string]: any;

    'orderType': WebullEquityLimitOrderPlaceQueryParamsOrderTypeEnum;
    'assetType'?: WebullEquityLimitOrderPlaceQueryParamsAssetTypeEnum;
    'action': WebullEquityLimitOrderPlaceQueryParamsActionEnum;
    'timeInForce': Timeinforce;
    'symbol': string;
    'orderQty': Orderqty4;
    'price': number;
    /**
     * Extended hours: N=regular only, Y=pre/post market
     */
    'supportTradingSession'?: WebullEquityLimitOrderPlaceQueryParamsSupportTradingSessionEnum | null;
    /**
     * When true, allow pre/post market. Used when supportTradingSession not set.
     */
    'extendedHours'?: boolean | null;
    /**
     * Idempotency key; server generates if omitted
     */
    'clientOrderId'?: string | null;
}

export enum WebullEquityLimitOrderPlaceQueryParamsOrderTypeEnum {
    Limit = 'limit'
}
export enum WebullEquityLimitOrderPlaceQueryParamsAssetTypeEnum {
    Equity = 'equity'
}
export enum WebullEquityLimitOrderPlaceQueryParamsActionEnum {
    Buy = 'buy',
    Sell = 'sell'
}
export enum WebullEquityLimitOrderPlaceQueryParamsSupportTradingSessionEnum {
    Y = 'Y',
    N = 'N'
}


